### ISSUE TITLE
[FEATURE] Configurable timeout for resources

### ISSUE THREAD

**Issue by lechnerc77** [SAP/terraform-provider-btp#11]
After phase 1 the Timeouts in the Terraform provider resources are hard coded. These timeouts should be made configurable.
This also comprises a discussion around SLAs.

**Comment by lechnerc77** [comment]
Essential for Kyma Environment

**Comment by lechnerc77** [comment]
See <https://developer.hashicorp.com/terraform/plugin/framework/resources/timeouts>

**Comment by lechnerc77** [comment]
Resources that need to be targeted for configurable timeouts (resource + command that needs to be enhanced)

Resource | CREATE | UPDATE | DELETE |
-- | -- | -- | -- | 
resource_directory | ✅ | ✅ | ✅
resource_subaccount_entitlement | ✅ | ✅ | ✅ 
resource_subaccount_environment_instance | ✅ | ✅ | ✅
resource_subaccount_service_binding | ✅ | n/a | ✅ 
resource_subaccount_service_instance | ✅ | ✅ | ✅ 
resource_subaccount_subscription | ✅ | n/a | ✅ 
resource_subaccount | ✅ | ✅ | ✅


Depends on #293 to have polling implemented consistently

**Comment by lechnerc77** [comment]
Additional remark: As we can only specify timeouts but not the `Delay` or `MinTimeOut` w must calculate these values based on the configurable timeout value

**Comment by aydin-ozcan** [comment]
Hi @lechnerc77 , 
Will the timeouts going to be effective both ways ?
On destruction of kyma , I get the timeout again .

> 
> btp_subaccount_environment_instance.kyma: Still destroying... [id=B63CBFF5-4970-4C97-8186-DA21FDA2DF2A, 10m0s elapsed]
> ╷
> │ Error: API Error Deleting Resource Environment Instance (Subaccount)
> │ 
> │ timeout while waiting for state to become 'DELETED, DELETION_FAILED' (last state: 'DELETING', timeout: 10m0s)
>

**Comment by lechnerc77** [comment]
@aydin-ozcan - FYI: This feature will take a bit more time than expected. In the meantime we changed the timeout for environment instances and services instances from 10 to 60 minutes. The change is available in the new release 0.3.0-beta1 (https://registry.terraform.io/providers/SAP/btp/0.3.0-beta1).

**Comment by lechnerc77** [comment]
Remark for development: currently data sources and resources might reuse the same internal data structure. This needs to be refactored as timeouts are only needed in resources.

**Comment by lechnerc77** [comment]
Breaking the customizing down to the two main resources that potentially cause issues:

  Resource | CREATE | UPDATE | DELETE |
-- | -- | -- | -- | 
resource_subaccount_environment_instance | ✅ | ✅ | ✅
resource_subaccount_service_instance | ✅ | ✅ | ✅

**Comment by lechnerc77** [comment]
Rebased branch <https://github.com/SAP/terraform-provider-btp/tree/feat-configurable-timeouts> and added types for data sources of entitlement without timeout in schema
