### ISSUE TITLE
[DOCU] Terraform tutorial at developers.sap.com

### ISSUE THREAD

**Issue by lechnerc77** [SAP/terraform-provider-btp#13]
In order to make the Terraform provider more visible and to lower the entry barrier we should offer a dedicated Terraform tutorial on  [developers.sap.com](https://developers.sap.com/tutorial-navigator.html).

**Comment by lechnerc77** [comment]
@v0lkc Looks good to me, please trigger the consequent steps to publish the tutorial

**Comment by v0lkc** [comment]
https://github.com/sap-tutorials/Tutorials/pull/23144

**Comment by v0lkc** [comment]
https://developers.sap.com/tutorials/btp-terraform-get-started.html
