### ISSUE TITLE
[BUG] add better error message if trust config exists in global account

### ISSUE THREAD

**Issue by rui1610** [SAP/terraform-provider-btp#189]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

If a user wants to create a trust configuration for a global account, and the account already has a trust configuration, the TF provider currently throws the following message:
`Error: API Error Creating Resource Trust Configuration (Global Account)
              with btp_globalaccount_trust_configuration.uut,
              on terraform_plugin_test.tf line 9, in resource "btp_globalaccount_trust_configuration" "uut":
               9: resource "btp_globalaccount_trust_configuration" "uut" {
            invalid character 'L' looking for beginning of value`

See as well https://github.com/SAP/terraform-provider-btp/pull/188 

### Describe the solution you would like

If a user wants to create a trust configuration for a global account, and the account already has a trust configuration, the TF provider should throw a message like e.g.
`can't create trust configuration for platform users in global account, as it is already set`

**Comment by v0lkc** [comment]
We had a similar issue already with resource providers (see NGPBUG-350117). This issue is likely caused by the underlying service and has to be reported to them.
