### ISSUE TITLE
[BUG] using capital letters for BTP region creates wrong terraform plan output

### ISSUE THREAD

**Issue by rui1610** [SAP/terraform-provider-btp#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

pre-release version

### What type of issue are you facing

bug report

### Describe the bug

When trying to execute a TF script for BTP with the region set to `US10` instead of `us10` the provider creates the following error message:

Error: API Error Creating Resource Subaccount

  with btp_subaccount.subaccount["dev-setup"],
  on main.tf line 15, in resource "btp_subaccount" "subaccount":
  15: resource "btp_subaccount" "subaccount" {

unexpected state '', wanted target 'OK, CREATION_FAILED, CANCELED'. last error: %!s(<nil>)

### Expected Behavior

Should either:
- raise an error that the region US10 doesn't exist
- lower case the region automatically before raising an error
- provide a list of available region values for the SAP BTP

### Steps To Reproduce

Create a TF script with the BTP region set to US10.

**Comment by v0lkc** [comment]
Once #219 is merged, it should look like this:

```bash
btp_subaccount.my_project: Creating...
╷
│ Error: API Error Creating Resource Subaccount
│ 
│   with btp_subaccount.my_project,
│   on resource.tf line 2, in resource "btp_subaccount" "my_project":
│    2: resource "btp_subaccount" "my_project" {
│ 
│ Region [EU12] is missing [Error: 20009/400]
╵
```
