### ISSUE TITLE
[DOCU] Impact of Firewall Setups

### ISSUE THREAD

**Issue by lechnerc77** [SAP/terraform-provider-btp#24]
To allow a smooth user experience when using the Terraform provider especially for new customers that have no experience with Terraform *per se* we should:

- [x] Evaluate if typical firewall setups in a company can cause issues when setting up the Terraform provider
- [x] If issues occur we need to document and give advice how to deal with them as part of the official documentation (arrea: provider setup)

**Comment by v0lkc** [comment]
In case of firewall issues, the traffic can also be routed via http/https proxies. All what needs to be done is, the user must set some proxy env vars according to the capabilities of the available proxy.

```
HTTP_PROXY=http://username:password@proxy.example.com
HTTPS_PROXY=http://username:password@proxy.example.com
