### ISSUE TITLE
[BUG] Unable to create subaccount within a directory

### ISSUE THREAD

**Issue by cerpass-86LAK** [SAP/terraform-provider-btp#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.1.0-beta1

### What type of issue are you facing

bug report

### Describe the bug

Unable to create a subaccount within a parent directory. Filling in the parent_id attribute with a directory id results in the following error.

![Screenshot 2023-06-30 093222](https://github.com/SAP/terraform-provider-btp/assets/124213814/277c6d9c-c48a-4a74-89d7-19f1d96aa5fd)

-Not sure if the image upload worked- the error I am receiving is below 

btp_subaccount.subaccount: Creating...
╷
│ Error: API Error Creating Resource Subaccount
│
│   with btp_subaccount.subaccount,
│   on main.tf line 47, in resource "btp_subaccount" "subaccount":
│   47: resource "btp_subaccount" "subaccount" {
│
│ Received response with unexpected status [Status: 400; Correlation ID:
│ xxxxxxxx-xxxx-xxx-xxxx-xxxxxxxxxxxx]

 where xxxxxxxx-xxxx-xxx-xxxx-xxxxxxxxxxxx is not the directory id of the parent.  I believe it is the ID of the subaccount which failed to create. 

Leaving the parent_id blank allows creation of subaccount under the global account and the error to go away. 

### Expected Behavior

Expected behavior is the subaccount being created under the parent directory supplied in the parent_id attribute. 

### Steps To Reproduce

1. using trial acc 
2. configure main.tf and provider appropriately
3. use the below resource block AND supply a directory guid

resource "btp_subaccount" "subaccount" {
  name      = "lak"
  subdomain = "lak"
  region    = "us10"
  parent_id = var.parentGUID
}

4.  terraform apply

**Comment by lechnerc77** [comment]
Thanks for reporting this issue. We can reproduce it and are working on a fix

**Comment by michael1011101** [comment]
Same issue here.
` Received response with unexpected status [Status: 400; Correlation ID: bd8ad0c1-2d8a-ea00-6fa9-af63b2a60f95]`

**Comment by lechnerc77** [comment]
Fixed with PR #259
