### ISSUE TITLE
[BUG] 2FA credentials failed during "terraform apply"

### ISSUE THREAD

**Issue by michael1011101** [SAP/terraform-provider-btp#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.1.0-beta1

### What type of issue are you facing

bug report

### Describe the bug

cli_server_url = "https://cpcli.cf.sap.hana.ondemand.com"

Unable to execute `terraform apply` or `terraform apply -auto-approve` to create the directories.
<img width="1088" alt="Screenshot 2023-07-03 at 15 46 25" src="https://github.com/SAP/terraform-provider-btp/assets/16817064/5ba3a8b8-7cc0-434f-8f04-5f4121fe0145">

### Expected Behavior

Expect the directories as the [sample usage](https://registry.terraform.io/providers/SAP/btp/latest/docs/resources/directory) shows to be created successfully.

### Steps To Reproduce

Terraform execution.
```
; terraform apply
var.global_account_user_name
  Enter a value: <my-emal>
var.global_account_user_password
  Enter a value: <password+2FA-code>
 
 ...
 Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

╷
│ Error: Unable to create Client
│ 
│   with provider["registry.terraform.io/sap/btp"],
│   on providers.tf line 22, in provider "btp":
│   22: provider "btp" {
│ 
│ Login failed. Check your credentials. [Status: 401; Correlation ID:
│ f43d8f57-1642-f16e-0288-737c0726614a]
╵
```

Provider scripts:
```
terraform {
  required_providers {
    btp = {
      source = "sap/btp"
      version = "0.1.0-beta1"
    }
  }
}

variable "global_account_user_name" {}
variable "global_account_user_password" {
  sensitive = true
}

provider "btp" {
  globalaccount = "<subdomain-of-global-account>"
  cli_server_url = "https://cpcli.cf.sap.hana.ondemand.com"
  username = var.global_account_user_name
  password = var.global_account_user_password
}
```

### Add screenshots to help explain your problem

`terraform plan` succeed.
<img width="1264" alt="Screenshot 2023-07-03 at 15 47 02" src="https://github.com/SAP/terraform-provider-btp/assets/16817064/d88917f3-5df2-4ef6-ac65-e982f43d4643">

`terraform apply` or `terraform apply -auto-approve` failed.
<img width="1088" alt="Screenshot 2023-07-03 at 15 46 25" src="https://github.com/SAP/terraform-provider-btp/assets/16817064/e090f15c-5ff5-4853-bf95-fd5854bb4c8a">

**Comment by lechnerc77** [comment]
Hi @michael1011101  the logon with a 2FA secured account and a logon procedure as used in case of the BTP CLI is not possible. Hence, please use a account without 2FA activated (either the existing one or one of a custom IdP. 

We are working on additional login flows but have no ETA for them.

**Comment by lechnerc77** [comment]
@P2007654252 HTP 401 means that you are not authorized to access the global account. Please check the following values are correct:

- **Subdomain** of the global account
- Username
- Password
- If you are using a custom IdP for authentication, make sure that the `idp` parameter is set correctly.
- If you are using SAP Universal ID, be aware of this section in the documentation as some adjustments need to be made there: [Link](https://registry.terraform.io/providers/SAP/btp/latest/docs#authentication)
