### ISSUE TITLE
[BUG] command `terraform destroy` failed with status 404

### ISSUE THREAD

**Issue by michael1011101** [SAP/terraform-provider-btp#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.1.0-beta1

### What type of issue are you facing

bug report

### Describe the bug

After creating the parent and child directories, I use the `terraform destroy` to remove all the resources terraform created. Then it failed with unexpected status -- Status 404.

Error message is as following.
```
Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

btp_directory.child: Destroying... [id=7240937c-8eef-48d0-aa63-3dca3e0320db]
╷
│ Error: API Error Deleting Resource Directory
│ 
│ Received response with unexpected status [Status: 404; Correlation ID: c72e8b16-a7b8-4905-3abc-d8eb474623c1]
╵
```

### Expected Behavior

From the BTP cockpit, the child directory was removed. But the state of the child directory was still in the terraform states.
```
; terraform state list
btp_directory.child
btp_directory.parent
```

Expected behavior is that both of the directories should be removed after executing `terraform destory`.

### Add screenshots to help explain your problem

Directories under the global account after executing `terraform apply`.
![Screenshot 2023-07-04 at 11 34 32](https://github.com/SAP/terraform-provider-btp/assets/16817064/3662b67f-fcb8-4637-879b-61f3215b9e79)

Directories after `terraform destroy` failed.
![Screenshot 2023-07-04 at 11 35 26](https://github.com/SAP/terraform-provider-btp/assets/16817064/2f09ad0f-2072-4e81-8f86-b6b9d23da65f)

**Comment by lechnerc77** [comment]
Thanks for reporting. This issue will be fixed with PR #264
