### ISSUE TITLE
[FEATURE] Get  Subaccount data source according to subdomain and region

### ISSUE THREAD

**Issue by michael1011101** [SAP/terraform-provider-btp#272]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

When creating the subaccount, we set the unique value of subdomain and region. But when getting the data source of the subaccount, we need to provide the subaccount id.
It is very strange for usage.

Reference
- [resource btp_subaccount](https://registry.terraform.io/providers/SAP/btp/latest/docs/resources/subaccount)
- [data source btp_subaccount](https://registry.terraform.io/providers/SAP/btp/latest/docs/data-sources/subaccount)

### Describe the solution you would like

Get the subaccount details according to the subdomain and region.

**Comment by lechnerc77** [comment]
The Terraform provider exposes the same logic as the BTP CLI which leads to the behavior you experience.

- The creation needs as input the subdomain and region (corresponding to <https://help.sap.com/docs/btp/btp-cli-command-reference/btp-create-accounts-subaccount>) and returns the ID of the subaccount as computed field.
- The data source representing the READ operation needs as input the  ID of the subaccount (corresponding to <https://help.sap.com/docs/btp/btp-cli-command-reference/btp-get-accounts-subaccount>).

**Comment by michael1011101** [comment]
Because of this, we had to wrap up the account service to implement this logic in a real scenario if we didn't persist the subaccount id. 
It is just a suggestion based on experience and might make it a little bit better. But thanks for you reply, and really agree with this -- The Terraform provider exposes the same logic as the BTP CLI.

**Comment by lechnerc77** [comment]
As you saw the issue remains open and might be implemented at a later point in time. By the way: the project is open source, so pull-requests are welcome.

**Comment by lechnerc77** [comment]
Workaround possible via data source `btp_subaccounts` encapsulated in a local module:

- variable definition

```terraform
variable "name" {
    type = string
    description = "The name of the subaccount"
}

variable "subdomain" {
  type = string
  description = "The subdomain of the subaccount"
}

variable "region" {
    type = string
    description = "The region of the subaccount"
}
```

- module definition

```terraform

terraform {
  required_providers {
    btp = {
      source  = "sap/btp"
      version = "0.5.0-beta1"
    }
  }
}

data "btp_subaccounts" "all" {}

locals {
  filtered_list = [for obj in data.btp_subaccounts.all.values : obj if obj.region == var.region && obj.subdomain == var.subdomain && obj.name == var.name]
}
```

- output definition


```terraform
output "subaccount_data" {
  value = local.filtered_list[0]
  description = "Subaccount data"
}
```
