### ISSUE TITLE
[FEATURE] Improve redaction of custom idp related values during fixture recording

### ISSUE THREAD

**Issue by kuntzed** [SAP/terraform-provider-btp#277]
search for "TODO #277" in the code

**Comment by lechnerc77** [comment]
Details of adjustments in `provider_test.go`:

1. the custom idp and issuer values should be redacted to some special value for now the custom idp is replaced by the empty string and the issuer by "accounts.sap.com" to keep existing fixtures working that were recorded without selecting a custom idp during login.
2. the custom idp header value should be redacted to some special value for now the header is replaced by the empty string to keep existing fixtures working that were recorded without selecting a custom idp during login
