### ISSUE TITLE
[BUG]: Provider produced inconsistent result after apply when changing the description of a subaccount

### ISSUE THREAD

**Issue by Lemonron** [SAP/terraform-provider-btp#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

1.5.2

### What type of issue are you facing

bug report

### Describe the bug

Changing the `description` of a `btp_subaccount` from `Managed by Terraform!` to `Managed by Terraform changed!` results in the following error when running `terraform apply`:

```bash
btp_subaccount.seoul: Modifying... [id=343cdaeb-215e-47e0-a009-eabbd9dce399]
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to btp_subaccount.seoul, provider "provider[\"registry.terraform.io/sap/btp\"]" produced an unexpected new value: .description: was cty.StringVal("Managed by
│ Terraform changed!"), but now cty.StringVal("Managed by Terraform!").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Expected Behavior

The description should be changed or the provider should report that update is not yet implemented.
Is there documentation on which actions are already supported for which resource type?

### Steps To Reproduce

1. Create a `btp_subaccount` with a `description`
2. Change the value of `description`
3. Run `terraform apply`

**Comment by lechnerc77** [comment]
Thanks for bringing this up. Issue is reproducible. 

Here sample setup:

provider.tf:

```hcl

terraform {
  required_providers {
    btp = {
      source  = "sap/btp"
      version = "0.1.0-beta1"
    }
  }
}

# Please checkout documentation on how best to authenticate against SAP BTP
# via the Terraform provider for SAP BTP
provider "btp" {
  globalaccount = "ticrossa"
}
```

main.tf:

```hcl
resource "btp_subaccount" "test_subaccount" {
  name        = "My TF Project"
  description = "My TF Project - renamed"
  subdomain   = "my-project"
  region      = "us10"
  labels      = { "Org" : ["my-org"] }
}
```
