### ISSUE TITLE
 Error: State Write Error on btp_subaccount_environment_instance import

### ISSUE THREAD

**Issue by aydin-ozcan** [SAP/terraform-provider-btp#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.1.0-beta1

### What type of issue are you facing

bug report

### Describe the bug

When provisioning Kyma, due to the existing issue ['Configurable timeout for resources'](https://github.com/SAP/terraform-provider-btp/issues/11), errors occur during the process after a hardcoded timeout of 10 minutes.

However, the provisioning continues and creates the Kyma environment, leaving the Terraform state inconsistent. To address this, I attempted to manually import the resource and update the state using the following command:

`
terraform import btp_subaccount_environment_instance.kyma   <subaccount>,<environment_instance_id>
`

During the import process, I encountered the following error:

> btp_subaccount_environment_instance.kyma: Importing from ID "26656678-7a82-42ae-aea7-1de71b7c4f92,FD03BA0B-BF5A-411E-B0F6-33DB0EC11926"...
data.btp_subaccount_environment_instances.all: Reading...
data.btp_subaccount_environment_instances.all: Read complete after 2s [id=26656678-7a82-42ae-aea7-1de71b7c4f92]
╷
│ Error: State Write Error
│ 
│ An unexpected error was encountered trying to retrieve type information at a given path. This is always an error in the provider. Please report the
│ following to the provider developer:
│ 
│ Error: AttributeName("subaccount") still remains in the path: could not find attribute or block "subaccount" in schema

I found an issue related to resource import: ['Import of existing resources'](https://github.com/SAP/terraform-provider-btp/issues/27). However, it's unclear if this feature has been implemented for the btp_subaccount_environment_instance.kyma resource yet  or if this is a bug. It would be helpful to receive a clear message indicating the current status of the import feature on a per-resource basis.

### Expected Behavior

The terraform import command should successfully import the resource and update the Terraform state without encountering the "State Write Error."

### Steps To Reproduce

1. Use the terraform-provider-btp to provision Kyma.
2. Observe the errors during the provisioning process.
3. Despite the errors, the Kyma environment is created, leaving the Terraform state inconsistent.
4. Attempt to manually import the resource using the provided command.
5. Encounter the "State Write Error" with the given error message.

### Additional context

BTP Trial account

**Comment by lechnerc77** [comment]
Hi @aydin-ozcan, 

thanks for bringing this to our atention. The import mapping of the keys is erronous in the current implementation and therefore the error you experience arises. We are working on a fix.

**Comment by lechnerc77** [comment]
Tasks for fix:

- [ ] Adjust import key to map the schema of the environment instance resource (subaccount vs. subsccount_id)
- [ ] Add the test and record a fixture for import (see e.g. `resource_subaccount_role_collection_test.go` for combined keys)
- [ ] Regnerate documentation

**Comment by lechnerc77** [comment]
To check; READ does not return parameters of environment instance - failure in validation of import data. 
API has specified it in its schema https://api.sap.com/api/APIProvisioningService/path/getEnvironmentInstance

**Comment by aydin-ozcan** [comment]
> 

Hi @lechnerc77 ,
Thanks for the quick response and your attention .
