### ISSUE TITLE
[FEATURE] enhance resource examples

### ISSUE THREAD

**Issue by v0lkc** [SAP/terraform-provider-btp#335]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

Some of the resource examples in the provider documentation can't be rolled out in a trial environment (e.g. `btp_subaccount_entitlement`).

```hcl
resource "btp_subaccount_entitlement" "alert_notification_service" {
  subaccount_id = "6aa64c2f-38c1-49a9-b2e8-cf9fea769b7f"
  service_name  = "alert-notification"
  plan_name     = "free"
}
```

`alert-notification:free` is not available in a trial environments, but `alert-notification:standard` is. 

### Describe the solution you would like

They shall be replaced with samples which can be rolled out in trial

**Comment by lechnerc77** [comment]
The check and adjustment of the examples for the feasibility/availability (including its regional dependency)  would be constant uphill battle with limited value for the user.

The goal should be that the examples work in PAYG accounts. Even here we might have issues as subscription and CPEA accounts might face different service availability even depending on the status of the subscriber (customer vs. TDDD of partners).

Closing this issue as wont-be-fixed
