### ISSUE TITLE
Hana instance creation failed

### ISSUE THREAD

**Issue by aydin-ozcan** [SAP/terraform-provider-btp#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.2.0-beta2

### What type of issue are you facing

bug report

### Describe the bug

Hana instance creation fails with the message below, but the process continues, and the instance is eventually created. I can import it to state later.

> btp_subaccount_service_instance.hana-cloud-trial: Creating...

> ╷
> │ Error: API Error Creating Resource Service Instance (Subaccount)
> │ 
> │   with btp_subaccount_service_instance.hana-cloud-trial,
> │   on hana.tf line 1, in resource "btp_subaccount_service_instance" "hana-cloud-trial":
> │    1: resource "btp_subaccount_service_instance" "hana-cloud-trial" {
> │ 
> │ invalid character 'U' looking for beginning of value

 Is this related to [33](https://github.com/SAP/terraform-provider-btp/issues/33) ?
 
 

### Additional context

BTP Trial

**Comment by lechnerc77** [comment]
@aydin-ozcan There is an issue with the API for the HANA instance creation that is called in the backend which is currently not returning a valid JSON format when creating an instance of the HANA Cloud instance. This results in the error you experience.

We are already following up on this in issue #33 and are still waiting for a fix. If you want to stay up to date with the progress, please subscribe to #33 to get informed when the fix will land in the provider.  I will therefore close this issue as a duplicate
