### ISSUE TITLE
[BUG] Subscribing to entitlement

### ISSUE THREAD

**Issue by cerpass-86LAK** [SAP/terraform-provider-btp#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.2.0-beta2

### What type of issue are you facing

bug report

### Describe the bug

![image](https://github.com/SAP/terraform-provider-btp/assets/124213814/06cc2220-71f6-45d3-b698-23fada9a944e)
Launchpad service creates successfully ~80% of the time. Other times the above error is shown. 

Occurs due to attempting to subscribe before the entitlement

### Expected Behavior

Should be successfully subscribing to the entitled resource 100% of the time. 

### Steps To Reproduce

resource "btp_subaccount_entitlement" "launchpad" {
   subaccount_id = btp_subaccount.subaccount.id
   service_name  = "SAPLaunchpad"
   plan_name     = "standard" 
}

resource "btp_subaccount_subscription" "launchpadService" {
  subaccount_id = btp_subaccount.subaccount.id
  app_name      = "SAPLaunchpad"
  plan_name     = "standard" 
}

run terraform apply with the above on trial account. 

### Additional context

![image](https://github.com/SAP/terraform-provider-btp/assets/124213814/c8fcfb22-ec21-4642-a14a-7d5b985a27b6)

when i graph the dependencies the below  can be seen
![image](https://github.com/SAP/terraform-provider-btp/assets/124213814/fabb86bd-41c8-4076-9b3d-0e8fd17f5154)

The subscription is not recognizing the dependency between the entitlement and the subscription unless explicitly told so using a depends_on block.

**Comment by lechnerc77** [comment]
Thanks for reporting. The behavior you describe is not a bug, but regular behavior of Terraform. The two resources cannot be automatically connected when Terraform calculates the execution plan as there is no connection between the resources except for the `subaccount_id`.
The solution is as you describe to make Terraform aware of the dependencies by adding a `depends_on` block in the dependent resource.
