### ISSUE TITLE
[BUG] Service instance by default getting created in other environment

### ISSUE THREAD

**Issue by shivakumar-p12-sap** [SAP/terraform-provider-btp#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.2.0-beta2

### What type of issue are you facing

documentation issue

### Describe the bug

Hi Team,

I have written the Terraform script to create a subaccount, create a cf environment, and then xsuaa service instance creation. By default, the service instance is getting created in other environment, and in the documentation, I don't see a way to specify in which platform that service instance has to be created. Please let me know if i missed something.

### Expected Behavior

There should be a way to specify the service instance platform in btp_subaccount_service_instance api, so that we can choose the platforms like cf, kyma or other.

### Steps To Reproduce

```
resource "btp_subaccount" "shivtestbtp" {
  name      = "Shivtestbtp"
  subdomain = "shiv-testbtp"
  region    = "eu12"
}

data "btp_whoami" "me" {}
resource "btp_subaccount_environment_instance" "cloudfoundry" {
  subaccount_id    = "${btp_subaccount.shivtestbtp.id}"
  name             = "my-env"
  environment_type = "cloudfoundry"
  service_name     = "cloudfoundry"
  plan_name        = "standard"
  landscape_label  = "cf-eu12"
  parameters = jsonencode({
    instance_name = "my-cf-org-name"
    users = [
      {
        id    = data.btp_whoami.me.id
        email = data.btp_whoami.me.email
      }
    ]
  })
}

resource "btp_subaccount_service_instance" "xsuaa_application" {
  subaccount_id  = "${btp_subaccount.shivtestbtp.id}"
  serviceplan_id = "de0d54b6-65bc-4817-a075-b038f7c150e4" 
  name           = "my-application"
}
```

### Add screenshots to help explain your problem

<img width="602" alt="image" src="https://github.com/SAP/terraform-provider-btp/assets/96462457/395996a5-a041-48ed-aa65-95a78d9667d4">

**Comment by lechnerc77** [comment]
In general Kubernetes-specific artifacts can be handled via the official Kubernetes provider (<https://registry.terraform.io/providers/hashicorp/kubernetes/latest>). 
Your scenario is targeting CRDs (namely the API `services.cloud.sap.com/v1`). To handle this you need to use the resource [kubernetes_manifest](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest). 

You find additional information in the official [documentation](https://developer.hashicorp.com/terraform/tutorials/kubernetes/kubernetes-crd-faas).

With respect to authentication with the Kyma Cluster, I recommend to create a [service account](https://kubernetes.io/docs/concepts/security/service-accounts/) and use the `kubeconfig` of this account.

I close this issue. If you have further question, please post them in the [Q&A area](https://github.com/SAP/terraform-provider-btp/discussions/categories/q-a) of the GitHub discussions in this repository.
