### ISSUE TITLE
btp_subaccount_environment_instance -> required key [instance_name]

### ISSUE THREAD

**Issue by tb000000** [SAP/terraform-provider-btp#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

latest version

### What type of issue are you facing

bug report

### Describe the bug

i want create a "cf-env-instance" and got the following error
In the provider documentation for ressource "btp_subaccount_environment_instance" is not a parameter "instance_name" described and not required.

### Expected Behavior

I expect the cf instance was created.
Or a better documentation how i create a cf-instance.
I think the option "parameter" is needed. 

### Steps To Reproduce

**My_Modul syntax**
module "environment_instance" {
  #source = "github.com/SAP-samples/btp-terraform-samples/released/modules/envinstance-cloudfoundry/"
  source = "../module_environment_instance/"

  subaccount_id         = btp_subaccount.sa.id
  env_instance_name     = local.subaccount_cf_orgname
  #cloudfoundry_org_name = local.subaccount_cf_orgname
  environment_type      = "cloudfoundry"
  service_name          = "cloudfoundry"
  plan_name             = "standard"
}

**Execute terraform apply**

**message i got**
_module.db_company_a["DEV"].module.environment_instance.btp_subaccount_environment_instance.env_instance: Creating...
╷
│ Error: API Error Creating Resource Environment Instance (Subaccount)
│
│   with module.db_company_a["DEV"].module.environment_instance.btp_subaccount_environment_instance.env_instance,
│   on module_environment_instance/main.tf line 3, in resource "btp_subaccount_environment_instance" "env_instance":
│    3: resource "btp_subaccount_environment_instance" "env_instance" {
│
│ Error when validating schema parameters: #: required key [instance_name] not found [Error: 11008/400]_

**Comment by lechnerc77** [comment]
Hi @tb000000 , 
the documentation for setting up a cloud foundry environment is described in the documentation for the resource [link](https://registry.terraform.io/providers/SAP/btp/latest/docs/resources/subaccount_environment_instance#example-usage).

However, you are not using the resource directly but are using a Terraform module. Concerning the parameters it is not one of the [samples repository](https://github.com/SAP-samples/btp-terraform-samples) although it is referenced but deactivated as source. 

To sort out which parameters are missing I would need the complete module definition especially the `variables.tf` and the `main.tf` of the module. You can directly attach the files to this issue via drag and drop.

**Comment by lechnerc77** [comment]
Clarification: The `parameters` part of the resource is marked as optional in the TF provider docu (see <https://registry.terraform.io/providers/SAP/btp/latest/docs/resources/subaccount_environment_instance>). As shown above it is not for the Cloud Foundry environment instance. We must validate if this is the case for Kyma and adjust the classification of the parameter. 

Minimum adoption is a clarification in the documentation and the example given.
