### ISSUE TITLE
[FEATURE] Nightly Builds

### ISSUE THREAD

**Issue by lechnerc77** [SAP/terraform-provider-btp#380]
The Terraform provider should provide a nightly build for the Terraform provider to provide preview versions.

**Comment by v0lkc** [comment]
Are you sure this is a good idea? We'd basically overflood the repo with tags nobody needs.

**Comment by lechnerc77** [comment]
I would have hoped for pre-releases with identical tag as `goreleaser` enables (<https://goreleaser.com/customization/nightlies/>). Unfortunately only in the commercial version. If we do not find a similar solution we can also leave it out

**Comment by lechnerc77** [comment]
No feasible option to realize this kind of build. Even if provided in the packages of GitHub, The setup at customer sites are quite unhandy - closing the issue.
