### ISSUE TITLE
[FEATURE] Drift detection for btp_subaccount_trust_configuration

### ISSUE THREAD

**Issue by sdischer-sap** [SAP/terraform-provider-btp#393]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

Currently updating the resource is not supported. We would require such behaviour for our use cases, specifically making sure that the configuration is recreated if it does not exist anymore. 

### Describe the solution you would like

Have support for updating all attributes of `btp_subaccount_trust_configuration` and recreate it if it has been removed externally.

**Comment by lechnerc77** [comment]
Fixed via #444 . In addition #492 fixes import issues. The full functionality will be available with release [0.6.0-beta1](https://github.com/SAP/terraform-provider-btp/milestone/9)
