### ISSUE TITLE
[FEATURE] Regression Test

### ISSUE THREAD

**Issue by lechnerc77** [SAP/terraform-provider-btp#409]
Implement regular regression testing based on re-recording the fixtures in a GH action run. 

Dependency to #59

**Comment by lechnerc77** [comment]
Blocked due to issue on IdP side - will be continued when fix is available on Canary landscape

**Comment by kuntzed** [comment]
SAP internal link: https://jira.tools.sap/browse/NGPBUG-374874

**Comment by vipinvkmenon** [comment]
We avoid the custom IPD setup in the regression test. 
Custom IDP can be explored in the integration test setup. #596

Closing this issue as resolved and implemented.
