### ISSUE TITLE
[REFACTORING] Reduce its Cognitive Complexity from 27 to the 15 allowed (Critical)

### ISSUE THREAD

**Issue by felixschirmer** [SAP/terraform-provider-btp#416]
SonarCloud finding:
https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&types=CODE_SMELL&id=SAP_terraform-provider-btp

**Comment by lechnerc77** [comment]
Resolved in Sonar Cloud as "wont fix" as the refactoring would not give any value. The nesting is okay in this scenario and the logic flow is comprehensive
