### ISSUE TITLE
Failed to load plugin schemas 

### ISSUE THREAD

**Issue by RCarvalhoSiemens** [SAP/terraform-provider-btp#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

1.5.7

### What type of issue are you facing

bug report

### Describe the bug

once we perform the command terraform plan we have an error 
"Failed to load plugin schemas"
│ Error while loading schemas for plugin components: Failed to obtain
│ provider schema: Could not load the schema for provider
│ registry.terraform.io/sap/btp: failed to instantiate provider
│ "registry.terraform.io/sap/btp" to obtain schema: could not find
│ executable file starting with terraform-provider-btp..

### Expected Behavior

excepted to run the command without any error message

### Steps To Reproduce

1. terraform init
2. terraform plan

### Add screenshots to help explain your problem

![terraform screenshot](https://github.com/SAP/terraform-provider-btp/assets/144708058/257ee418-5e62-4925-a64b-2fce55e66800)

**Comment by lechnerc77** [comment]
@RCarvalhoSiemens : The dev container provided in this repository contains a developer override that causes the issue. It is intended for developers *contributing to the provider code base* and exploring the provider from a *local build* (see also [developer documentation](https://github.com/SAP/terraform-provider-btp/blob/main/DEVELOPER.md)). If this is the case please first build the provider locally.

If you want to test the provider that is officially available in the Terraform registry, you can either use a local installation of the Terraform CLI, or you reuse one the dev containers that are available in the [samples repository](https://github.com/SAP-samples/btp-terraform-samples). Here not dev override is in place and the provider gets fetched from the Terraform registry.
