### ISSUE TITLE
[BUG] Kyma instance cannot be created "User is unauthorized for this operation [Error: 11004/405]"

### ISSUE THREAD

**Issue by SeanKilleen** [SAP/terraform-provider-btp#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

1.5.6

### What type of issue are you facing

bug report

### Describe the bug

Showed this while on a call with @lechnerc77 and he confirmed I should probably add it here.

## Background

* I am in a global account administrator role
* I am also in a sub-account administrator role
* The sub-account already has a CloudFoundry environment (not sure if that's relevant)
* I have enabled the Kyma entitlement via Terraform previously.
* I can create a Kyma environment manually via the BTP Cockpit UI.

## Problem 

I am unable to create a Kyma resource, e.g.

```tf
resource "btp_subaccount_environment_instance" "kyma" {
  subaccount_id    = btp_subaccount.products.id
  name             = "sct-products-kyma"
  environment_type = "kyma"
  service_name     = "kyma"
  plan_name        = "aws"

  parameters = jsonencode({
    name   = "sct-products-kyma"
    region          = "us-east-1"
    machine_type    = "mx5.xlarge" #smallest option
    auto_scaler_min = 3
    auto_scaler_max = 20
  })
}
```
When I run terraform apply, I receive the error:

> │ Error: API Error Creating Resource Environment Instance (Subaccount)
> │
> │   with module.product_environment.module.product_environment_btp.btp_subaccount_environment_instance.kyma,
> │   on modules\product_environment_btp\main.tf line 92, in resource "btp_subaccount_environment_instance" "kyma":
> │   92: resource "btp_subaccount_environment_instance" "kyma" {
> │
> │ User is unauthorized for this operation [Error: 11004/405]

### Expected Behavior

I should be able to create a Kyma environment within a sub-account.

### Steps To Reproduce

- Terraform init
- Create a resource/reference for a sub-account.
- Already have a CF environment set up in the sub-account (mentioning here in case it's relevant)
- Enable Kyma entitlement (in my case, I did this via Terraform)
- Add a kyma resource, e.g. in the same I have above
- Attempt `terraform apply`

**Comment by lechnerc77** [comment]
@SeanKilleen just cross-checked the parameters you mentioned above and the PR you referenced. Can you crosscheck that for  `service_name`  the value is "kymaruntime"? 

As additional info based on our discussion you find the available parameters for Kyma here depending on your landscape and plan here : <https://help.sap.com/docs/btp/sap-business-technology-platform/available-plans-in-kyma-environment>

**Comment by SeanKilleen** [comment]
Hi @lechnerc77 -- just to confirm, you're saying that in my Terraform service instance definition, the `environment_type` should be `kyma`, and the `service_name` should be `kymaruntime`?

If so, that's the likely culprit. I didn't have the docs example so I assumed both values would be `kyma`, much as the other values were `cloudfoundry`. But I do see that in the service entitlement definition, it is called `kymaruntime`, so that could absolutely be the discrepancy.

I'm not in a position to teardown the Kyma cluster I'm working with currently, but as soon as I can, I will do so and then attempt to recreate it with this.

**Comment by lechnerc77** [comment]
Yes that's right. The service name is kymaruntime (instead of kyma).

**Comment by SeanKilleen** [comment]
@lechnerc77 SUCCESS! 🎉 I'm so sorry that I missed that detail. After updating the service name (by making it a reference to the service entitlement's service name, so that it's clear), the operation appears to be in progress and I've received no errors.

Thank you for your support. I'll also update #430 to ensure it's correct.

**Comment by lechnerc77** [comment]
Great to hear that - no worries I missed that too during our session. #430 is already in the right shape.
