### ISSUE TITLE
[FEATURE] Ability to Share Service Instances

### ISSUE THREAD

**Issue by SeanKilleen** [SAP/terraform-provider-btp#437]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

I'm moving from a CloudFoundry environment into a Kyma environment, and it would be very helpful to enable a service to be consumed by both Kyma (via BTP Service Operator) and CloudFoundry at the same time.

My understanding is that this can be done via the [btp share services/instance command on the BTP CLI](https://help.sap.com/docs/btp/btp-cli-command-reference/btp-share-services-instance). However, I can't find any way to do this with the existing BTP TF provider. One can read whether the service is shared, but cannot set whether it is shared. As a result, I have to share the service via the BTP CLI as a separate command in order to then pick up the service in my Kyma environment Terraform.

### Describe the solution you would like

On the [`subaccount_service_instance` resource](https://registry.terraform.io/providers/SAP/btp/latest/docs/resources/subaccount_service_instance), I think it would make sense to have a value, `shared`, that defaults to `false`. When set to `true`, is reconciled by performing this command.

**Comment by lechnerc77** [comment]
@SeanKilleen Thanks for the valuable feedback. I added this to our backlog. 

Please be aware that the described sharing of service instances is service-dependent, so your approach must be validated against the different services in your solution

**Comment by SeanKilleen** [comment]
@lechnerc77 thanks - I did come to that conclusion as well. There did not seem to be any easy way to tell which services were shareable. I ended up moving my Kyma instance into its own subaccount to create a new credstore instance that we can move to. And, the BTP terraform was quite useful in that, so thank you!

**Comment by SeanKilleen** [comment]
It looks like I may have been able to achieve this had I used a different parameter. https://answers.sap.com/questions/13976090/sharing-a-credential-store-instance-between-cloudf.html?childToView=13984730

Since we're all in on Kyma, I won't be able to explore this further. I'm fine if it's closed because it doesn't represent a realistic backlog item.

**Comment by lechnerc77** [comment]
The way forward you referenced is implementing the sharing via referencing it in the BTP service operator running in Kyma. This is one option, but I will leave this request open to check if there is the demand to include this BTP CLI command into the Terraform provider.
