### ISSUE TITLE
Terraform btp_subaccount creation fails[BUG]

### ISSUE THREAD

**Issue by prajin-op** [SAP/terraform-provider-btp#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.2.0-beta2

### What type of issue are you facing

bug report

### Describe the bug

Hello Colleagues,

We are currently facing an issue when using Terraform to create an SAP BTP subaccount with entitlements. The terraform apply command is failing with the following error:

Error: API Error Creating Resource Subaccount

Received response with unexpected status [Status: 500; Correlation ID: 24cc91e9-c305-2ad0-951e-7fd1bb57b745]

Despite the error, when we check the SAP BTP subaccount, it appears to have been created successfully.

Please find the error details below

Terraform will perform the following actions:
  + resource "btp_subaccount" "btpauto-new" {
      + beta_enabled    = (known after apply)
      + created_by      = (known after apply)
      + created_date    = (known after apply)
      + description     = (known after apply)
      + id              = (known after apply)
      + labels          = (known after apply)
      + last_modified   = (known after apply)
      + name            = "btpauto-new"
      + parent_features = (known after apply)
      + parent_id       = (known after apply)
      + region          = "eu12"
      + state           = (known after apply)
      + subdomain       = "btpauto-new"
      + usage           = (known after apply)
    }
  + resource "btp_subaccount_entitlement" "bas" {
      + amount        = (known after apply)
      + category      = (known after apply)
      + created_date  = (known after apply)
      + id            = (known after apply)
      + last_modified = (known after apply)
      + plan_id       = (known after apply)
      + plan_name     = "standard"
      + service_name  = "sapappstudio"
      + state         = (known after apply)
      + subaccount_id = (known after apply)
    }
  + resource "btp_subaccount_entitlement" "build_workzone" {
      + amount        = (known after apply)
      + category      = (known after apply)
      + created_date  = (known after apply)
      + id            = (known after apply)
      + last_modified = (known after apply)
      + plan_id       = (known after apply)
      + plan_name     = "standard"
      + service_name  = "SAPLaunchpad"
      + state         = (known after apply)
      + subaccount_id = (known after apply)
    }
  + resource "btp_subaccount_entitlement" "hana-cloud-tools" {
      + amount        = (known after apply)
      + category      = (known after apply)
      + created_date  = (known after apply)
      + id            = (known after apply)
      + last_modified = (known after apply)
      + plan_id       = (known after apply)
      + plan_name     = "tools"
      + service_name  = "hana-cloud-tools"
      + state         = (known after apply)
      + subaccount_id = (known after apply)
    }
  + resource "btp_subaccount_environment_instance" "cloudfoundry" {
      + broker_id        = (known after apply)
      + created_date     = (known after apply)
      + custom_labels    = (known after apply)
      + dashboard_url    = (known after apply)
      + description      = (known after apply)
      + environment_type = "cloudfoundry"
      + id               = (known after apply)
      + labels           = (known after apply)
      + landscape_label  = "cf-eu12"
      + last_modified    = (known after apply)
      + name             = "my-env"
      + operation        = (known after apply)
      + parameters       = jsonencode(
            {
              + instance_name = "my-cf-org-name"
              + users         = [
                  + {
                      + email = "prajin.ollekkatt.prakasan@sap.com"
                      + id    = "prajin.ollekkatt.prakasan@sap.com"
                    },
                ]
            }
        )
      + plan_id          = (known after apply)
      + plan_name        = "standard"
      + platform_id      = (known after apply)
      + service_id       = (known after apply)
      + service_name     = "cloudfoundry"
      + state            = (known after apply)
      + subaccount_id    = (known after apply)
      + tenant_id        = (known after apply)
      + type             = (known after apply)
    }

Plan: 5 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
  Enter a value: yes
btp_subaccount.btpauto-new: Creating...
╷
│ Error: API Error Creating Resource Subaccount
│
│   with btp_subaccount.btpauto-new,
│   on btp.tf line 2, in resource "btp_subaccount" "btpauto-new":
│    2: resource "btp_subaccount" "btpauto-new" {
│
│ Received response with unexpected status [Status: 500; Correlation ID: 24cc91e9-c305-2ad0-951e-7fd1bb57b745]

<img width="777" alt="image" src="https://github.com/SAP/terraform-provider-btp/assets/71236507/56a0ba89-c562-4296-9c4b-9883ce33eb0a">

<img width="640" alt="image" src="https://github.com/SAP/terraform-provider-btp/assets/71236507/19ce845e-3ce8-4f77-a608-fe3a18d5b96f">

Link to the config files: https://github.tools.sap/I572426/btp-terraform-sample/blob/main/btp.tf

Can someone help us to identify this issue?

Regards,
Prajin

**Comment by lechnerc77** [comment]
@prajin-op Can you please validate the issue with the latest version of the provider <https://registry.terraform.io/providers/SAP/btp/latest>. Thanks
