### ISSUE TITLE
[FEATURE] Detect and fix state drifts

### ISSUE THREAD

**Issue by biehlera** [SAP/terraform-provider-btp#442]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

No matter if I create a subaccount or a folder with terraform and manually delete one of the objects in the BTP, the provider aborts with an error message that the deleted object cannot be found. 

Error: API Error Reading Resource Directory
│
│   with btp_directory.child,
│   on all.tf line 43, in resource "btp_directory" "child":
│   43: resource "btp_directory" "child" {
│
│ Could not find 922cbacb-2849-4bc3-bfc6-2ece60e5534c [Error: 20002/404]

### Describe the solution you would like

The expectation would be that terraform would recognize such state drifts and fix them instead of aborting.

**Comment by lechnerc77** [comment]
@biehlera thanks for the request. The manual deletion of resources is a scenario that cannot be handled generically as an automatic re-creation can cause side-effects on other resources. 

To resolve scenarios with a manual deletion you have two options:

1. Re-create the resource manually and import it with the same address to the Terraform state (see [Terraform documentation - import](https://developer.hashicorp.com/terraform/language/import)).
2. Remove the state from your state file and reapply the configuration:
   1. List the addresses of your resources in the state via `terraform state list` -> identify the right address
   2. Remove the resources from your state via `terraform state rm <resource address>` (you have the option `--dry-run` to check what will be removed)
   3. Reapply the configuration via `terraform plan` and `terraform apply`which will recreate the manually deleted resource.
