### ISSUE TITLE
[ANALYSIS] Validate setup with OpenTofu

### ISSUE THREAD

**Issue by lechnerc77** [SAP/terraform-provider-btp#460]
[OpenTofu](https://opentofu.org/) is positioned as alternative and at least until now as a drop-in replacement for Hashicorps Terraform.

Once a beta version of the setup is published (see [releases](https://github.com/opentofu/opentofu/releases)), we should validate our provider against this setup i.e.

- Can we provide the provider via the OpenTofu registry setup
- Can we use the provider via OpenTofu CLI 

Depending on the outcome of the analysis follow-up steps can be discussed

**Comment by lechnerc77** [comment]
As long as OpenTofu is not available as `beta` version, this issue is blocked

**Comment by Yantrio** [comment]
Hi @lechnerc77 👋 

I'm one of the core developers working on the opentofu registry.

In theory everything should just work out of the box, if you hit any issues please feel free to reach out to myself or raise an issue in https://github.com/opentofu/registry

Right now the OpenTofu registry does not have access to everybody's GPG Keys, so we are asking providers to upload their keys to the registry. Instructions on how to do that are here: https://github.com/opentofu/registry#adding-a-public-key. 

This is a purely optional step, as we will still allow people to consume the provider through OpenTofu, but just without key validation.

**Comment by lechnerc77** [comment]
Hi @Yantrio ,

nice to virtually meet you. Thanks for the heads up and the additional information on setting up the registry. 

Do you know if there is a official timeline wrt to bringing OpenTofu to beta?

**Comment by Yantrio** [comment]
I don't have an official date right now, but work is going quickly.

Our current releases are marked as `alpha`, but they are ready to be tested. I suspect we may not have a `beta` phase before a stable release.

For now you can follow our work towards the first stable release here: https://github.com/opentofu/opentofu/milestone/3

We're moving fast and I suspect this should be pretty soon!

**Comment by lechnerc77** [comment]
Ah okay, I would have assumed a beta phase, but that changes things a bit. Then I will put that into the backlog again. We will probably put that into one of the next two sprints. I will post an update on our result in this issue.

**Comment by lechnerc77** [comment]
Terraform registry RFC is accepted and on its way to be implemented: <https://github.com/opentofu/opentofu/issues/741>

**Comment by lechnerc77** [comment]
GA release is available: https://opentofu.org/blog/opentofu-is-going-ga.
Reevaluation possible.

**Comment by lechnerc77** [comment]
Revalidated the setup with OpenTofu via a dev container feature and a local setup. No issues, so for GA version 1.6.0 of OpenTofu the provider seems to be compliant. 

The process to register the provider is described in the registry repository (<https://github.com/opentofu/registry>).

Closing this issue and waiting for feedback from our customers and partners if OpenTofu should be officially supported which comes with several organizational follow-up activities from our side.

**Comment by Yantrio** [comment]
Hi @lechnerc77 ! Glad to hear everything went okay.

As for registering the provider, this provider was already included as part of our initial opentofu hydration process. And the provider is available to be used today by opentofu users already.

You can find information about your releases here: https://github.com/opentofu/registry/blob/main/providers/s/SAP/btp.json and we will automatically keep this up to date.

However, in the future if you do have any providers to register, you can follow the instructions in the README here: https://github.com/opentofu/registry/blob/main/README.md

There is also instructions there about how you can upload your GPG key so that your providers can be verified 👍 

Please feel free to reach out if you do hit any issues.

**Comment by lechnerc77** [comment]
Hi @Yantrio thanks for the heads-up. 
The last time I checked at the very early days of the registry it wasn't there or I looked at the wrong spot.
The verification from our side is then tied to the menrioned internal clarification. Nevertheless I have some questions related to that official support of the provider from our side. Can I reach out to you via the OpenTofu Slack?

**Comment by Yantrio** [comment]
Sure, I'll reach out to you with a DM. 

The registry truely has come a long way and now is extremely stable and filled with all sorts of great providers and modules :D
