### ISSUE TITLE
[BUG] "No data source type named "btp_directory" was found in the provider" since 0.5.0-beta1

### ISSUE THREAD

**Issue by olfolfolf** [SAP/terraform-provider-btp#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.5.0-beta1

### What type of issue are you facing

bug report

### Describe the bug

I got the following error since 0.5.0-beta1:

```
│ Error: Data Source Type Not Found
│
│   with data.btp_directory.dir_integration_suite,
│   on subaccount.tf line 4, in data "btp_directory" "dir_integration_suite":
│    4: data "btp_directory" "dir_integration_suite" {
│
│ No data source type named "btp_directory" was found in the provider.
```

tf-file looks like this:
```
data "btp_directory" "dir_integration_suite" {
  id = "....."
}
```

When I change the provider back to 0.4.0-beta1, the error is gone.

Same happens to data source type "btp_whoami".

### Steps To Reproduce
```
terraform {
  required_providers {
    btp = {
      source  = "SAP/btp"
      version = "0.5.0-beta1"
    }
  }
}
```

```
data "btp_directory" "dir_integration_suite" {
  id = "....."
}
```

**Comment by lechnerc77** [comment]
@olfolfolf Can you please check which version of the Terraform CLI you are using? If it is version 1.6.x then this is a known issue described here incl. the possible workaround: <https://github.com/SAP/terraform-provider-btp/discussions/477>

**Comment by olfolfolf** [comment]
Yes, I'm using 1.6.
Sorry, searched for the data source type, not for the message.
