### ISSUE TITLE
[BUG] Terraform 1.6.x Fails due to plugin framework issue

### ISSUE THREAD

**Issue by SeanKilleen** [SAP/terraform-provider-btp#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

1.6.2

### What type of issue are you facing

bug report

### Describe the bug

After upgrading go Terraform v1.6.x, I receive errors along the lines of `No data source type named "btp_directory" was found in the provider.`

If the SAP BTP team is building the terraform plugin on the v1.4.x provider, you may need to update to the latest bugfix or roll back to 1.3.x in order to resolve this

Reference: https://github.com/hashicorp/terraform/issues/33990

For now, I have to downgrade my Terraform to v1.5.x in order to work with the BTP providers it seems.

**Comment by lechnerc77** [comment]
Hi @SeanKilleen ,

yes this is a known limitation at the moment. The fix is already implemented and will be shipped with the next release.

For details and workarounds see <https://github.com/SAP/terraform-provider-btp/discussions/477>.

**Comment by SeanKilleen** [comment]
Thanks, and sorry for the duplicate! I checked the issues but missed it somehow.
