### ISSUE TITLE
[BUG] no resource type named "btp_subaccount" was found in the provider

### ISSUE THREAD

**Issue by marcohoepner** [SAP/terraform-provider-btp#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

Terraform version: 1.6.2

### What type of issue are you facing

bug report

### Describe the bug

I would like to add a new subaccount to btp globalaccount

Error: Resource Type Not Found
│
│   with btp_subaccount.fred,
│   on main.tf line 1, in resource "btp_subaccount" "fred":
│    1: resource "btp_subaccount" "fred" {
│
│ No resource type named "btp_subaccount" was found in the provider.

### Expected Behavior

get a new subaccount

### Steps To Reproduce

terraform init
terraform plan

provider.tf

terraform {
  required_providers {
    btp = {
      source  = "SAP/btp"
      version = "0.5.0-beta1"
    }
    cloudfoundry = {
      source  = "cloudfoundry-community/cloudfoundry"
      version = "0.51.3"
    }
  }
}

variable "admin_user" {}
variable "admin_password" {}
variable "globalaccount_subdomain" {}

# Configure the BTP Provider
provider "btp" {
  globalaccount = var.globalaccount_subdomain
    username      = var.admin_user
    password      = var.admin_password
}

# Cloud Foundry provider configuration
provider "cloudfoundry" {
  api_url  = "https://api.cf.eu20-001.hana.ondemand.com"
  user     = var.admin_user
  password = var.admin_password
}

Using main.tf

resource "btp_subaccount" "fred" {
  name      = "Fred's Project"
  subdomain = "freds-project"
  region    = "eu20"
}

### Additional context

[terraform.txt](https://github.com/SAP/terraform-provider-btp/files/13188476/terraform.txt)

**Comment by lechnerc77** [comment]
@marcohoepner this is a known limitation. Please downgrade to version 1.5.7 of the Terraform CLI. A fix will be delivered in the next release in November. For details see <https://github.com/SAP/terraform-provider-btp/discussions/477>

**Comment by marcohoepner** [comment]
ok.

thank you
