### ISSUE TITLE
[BUG]Error: API Error Creating Resource Role Collection Assignment (Subaccount)

### ISSUE THREAD

**Issue by dineshkumarbcs** [SAP/terraform-provider-btp#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.2.0-beta2

### What type of issue are you facing

bug report

### Describe the bug

I am trying to create a terraform for user automation alone. I am getting the plan as below.

 

Terraform will perform the following actions:

# btp_subaccount_role_collection_assignment.bas_admn["test2@test.com"] will be created
+ resource "btp_subaccount_role_collection_assignment" "bas_admn" {
+ id = (known after apply)
+ origin = "ldap"
+ role_collection_name = "Business_Application_Studio_Administrator"
+ subaccount_id = "5ec57e8d-be52xxx"
+ user_name = "test2@test.com"
}

# btp_subaccount_role_collection_assignment.bas_admn["test3@test.com"] will be created
+ resource "btp_subaccount_role_collection_assignment" "bas_admn" {
+ id = (known after apply)
+ origin = "ldap"
+ role_collection_name = "Business_Application_Studio_Administrator"
+ subaccount_id = "5ec57e8d-bxxx"
+ user_name = "test3@test.com"
}

# btp_subaccount_role_collection_assignment.bas_dev["test1@test.com"] will be created
+ resource "btp_subaccount_role_collection_assignment" "bas_dev" {
+ id = (known after apply)
+ origin = "ldap"
+ role_collection_name = "Business_Application_Studio_Developer"
+ subaccount_id = "5ec57e8d-bexxxx"
+ user_name = "test1@test.com"
}

# btp_subaccount_role_collection_assignment.bas_dev["test2@test.com"] will be created
+ resource "btp_subaccount_role_collection_assignment" "bas_dev" {
+ id = (known after apply)
+ origin = "ldap"
+ role_collection_name = "Business_Application_Studio_Developer"
+ subaccount_id = "5ec57e8d-bexxxx"
+ user_name = "test2@test.com"
}

# time_sleep.wait_a_few_seconds will be created
+ resource "time_sleep" "wait_a_few_seconds" {
+ create_duration = "5s"
+ id = (known after apply)
}

Plan: 5 to add, 0 to change, 0 to destroy.

 

But when I execute the apply only first entries are getting added and remaining all are failing with 500 error. I tried even giving exact value instead of var files. Still the same.

 

Do you want to perform these actions?
Terraform will perform the actions described above.
Only 'yes' will be accepted to approve.

Enter a value: yes

time_sleep.wait_a_few_seconds: Creating...
time_sleep.wait_a_few_seconds: Creation complete after 5s [id=2023-11-06T11:46:25Z]
btp_subaccount_role_collection_assignment.bas_admn["test2@test.com"]: Creating...
btp_subaccount_role_collection_assignment.bas_dev["test1@test.com"]: Creating...
btp_subaccount_role_collection_assignment.bas_admn["test3@test.com"]: Creating...
btp_subaccount_role_collection_assignment.bas_dev["test2@test.com"]: Creating...
btp_subaccount_role_collection_assignment.bas_admn["test2@test.com"]: Creation complete after 2s [id=5ec57e8d-be52-47c3-8274-7cc86ef51f4f,Business_Application_Studio_Administrator,test2@test.com]
╷
│ Error: API Error Creating Resource Role Collection Assignment (Subaccount)
│
│ with btp_subaccount_role_collection_assignment.bas_dev["test1@test.com"],
│ on main.tf line 28, in resource "btp_subaccount_role_collection_assignment" "bas_dev":
│ 28: resource "btp_subaccount_role_collection_assignment" "bas_dev" {
│
│ Received response with unexpected status [Status: 500; Correlation ID: dab78805-82d1-2ed5-9d94-e1ba4a91e1e5]
╵
╷
│ Error: API Error Creating Resource Role Collection Assignment (Subaccount)
│
│ with btp_subaccount_role_collection_assignment.bas_dev["test2@test.com"],
│ on main.tf line 28, in resource "btp_subaccount_role_collection_assignment" "bas_dev":
│ 28: resource "btp_subaccount_role_collection_assignment" "bas_dev" {
│
│ Received response with unexpected status [Status: 500; Correlation ID: 74a24b54-2ae6-a671-5605-5d7e5208eff1]
╵
╷
│ Error: API Error Creating Resource Role Collection Assignment (Subaccount)
│
│ with btp_subaccount_role_collection_assignment.bas_admn["test3@test.com"],
│ on main.tf line 36, in resource "btp_subaccount_role_collection_assignment" "bas_admn":
│ 36: resource "btp_subaccount_role_collection_assignment" "bas_admn" {
│
│ Received response with unexpected status [Status: 500; Correlation ID: b5ca147a-f72c-8982-c134-b888d8847da3]
╵

I am not sure whether this is bug or I am having any library missing. Please help.

### Expected Behavior

All planned entries were supposed to be executed

**Comment by dineshkumarbcs** [comment]
Forgot to mention, if I keep executing repeatedly (Apply again and again) the same it is perform each one by one. Which means only one entries are keep adding. The same error appears even for destroy.

**Comment by lechnerc77** [comment]
@dineshkumarbcs: Please check the following points and retry the execution of the script:

1. You are using an outdated version of the provider. Please upgrade to version 0.5.0-beta1
2. Please verify that the subaccount has an entitlement for the Business Application studio
3. Please verify that the role collections exist in the subaccount (usually the prerequisite for this is that a service instance of BAS is existing in the subaccount
4. The `time.sleep` resource shouldn't be needed in your case. I do not see any reason from your description why the execution should wait.

**Comment by Irfanaj** [comment]
terraform {
  required_providers {
    btp = {
      source  = "sap/btp"
      version = "0.5.0-beta1"
    }
  }
}

  provider "btp" {
  globalaccount =  var.globalaccount
  username      = "dinesh.kumar@basiscloudsolutions.com"
  password      = "Din1@3esh"
}

# assign a single user to a role collection on directory level

resource "btp_subaccount_role_collection_assignment" "subaccount-Administrator"  {
  
  subaccount_id         = "5ec57e8d-be52-47c3-8274-7cc86ef51f4f"
  role_collection_name = "Subaccount Administrator"
  user_name            = "test1@basiscloudsolutions.com"
} 
resource "btp_subaccount_role_collection_assignment" "Subaccount-Service-Administrator" {

  subaccount_id         = "5ec57e8d-be52-47c3-8274-7cc86ef51f4f"
  role_collection_name = "Subaccount Administrator"
  user_name            = "test2@basiscloudsolutions.com"
}

when I change the provider to the latest version "0.5.0-beta1" I am receiving the following error

Error: Resource Type Not Found
│
│   with btp_subaccount_role_collection_assignment.subaccount-Administrator,
│   on main.tf line 18, in resource "btp_subaccount_role_collection_assignment" "subaccount-Administrator":
│   18: resource "btp_subaccount_role_collection_assignment" "subaccount-Administrator"  {
│
│ No resource type named "btp_subaccount_role_collection_assignment" was found in the provider.
╵
╷
│ Error: Resource Type Not Found
│
│   with btp_subaccount_role_collection_assignment.Subaccount-Service-Administrator,
│   on main.tf line 24, in resource "btp_subaccount_role_collection_assignment" "Subaccount-Service-Administrator":
│   24: resource "btp_subaccount_role_collection_assignment" "Subaccount-Service-Administrator" {
│
│ No resource type named "btp_subaccount_role_collection_assignment" was found in the provider.

**Comment by lechnerc77** [comment]
@Irfanaj  @dineshkumarbcs : Short update: I just released the new version of the Terraform provider namely version 0.6.0-beta1. I recommend to switch to this version.  
@Irfanaj ; version 0.6.0-beta1 is compatible with Terraform CLI 1.6.x

**Comment by dineshkumarbcs** [comment]
Thank you so much. It works as expected.

**Comment by lechnerc77** [comment]
@dineshkumarbcs So can we close the issue?

**Comment by dineshkumarbcs** [comment]
Yes Please.
