### ISSUE TITLE
[BUG] Unable to add entitlements to subaccount in a managed directory

### ISSUE THREAD

**Issue by tcasteli** [SAP/terraform-provider-btp#537]
When adding entitlements to a subaccount in a managed directory I am getting the following error:

> btp_subaccount_entitlement.bas: Creating...
> ╷
> │ Error: API Error Creating Resource Entitlement (Subaccount)
> │ 
> │   with btp_subaccount_entitlement.bas,
> │   on btp.tf line 74, in resource "btp_subaccount_entitlement" "bas":
> │   74: resource "btp_subaccount_entitlement" "bas" {
> │ 
> │ the backend responded with an unknown error: 403

However, I am able to add the entitlement manually.

**Comment by lechnerc77** [comment]
Can you please add your the following information to the issue:

- What version of Terraform CLI are you using?
- What version of the Terraform provider are you using?
- The complete Terraform configuration you are using

**Comment by tcasteli** [comment]
Terraform version 1.6.3
Provider version 0.6.0-beta2

config:
`terraform {
  required_providers {
    btp = {
      source  = "sap/btp"
      version = "0.6.0-beta2"
    }
    cloudfoundry = {
      source  = "cloudfoundry-community/cloudfoundry"
      version = "0.51.3"
    }
  }
}

variable "btp_user_information" {
  type = object({
    username = string
    password = string
  })
  sensitive = true
}

provider "btp" {
  globalaccount = "<some-account>"
  username      = var.btp_user_information.username
  password      = var.btp_user_information.password
}

provider "cloudfoundry" {
  api_url  = "https://api.cf.eu10-004.hana.ondemand.com"
  user     = var.btp_user_information.username
  password = var.btp_user_information.password
}

# Create a subaccount
resource "btp_subaccount" "dev-finance" {
  name        = "dev-finance-ext"
  subdomain   = "dev-finance-ext"
  parent_id   = "<parent-id>"
  region      = "eu10"
  description = "Finance development subaccount, maintained by Terraform"
}

# Enable cloud foundry & create org
resource "btp_subaccount_environment_instance" "cloudfoundry" {
  subaccount_id    = btp_subaccount.dev-finance.id
  name             = "finance"
  environment_type = "cloudfoundry"
  service_name     = "cloudfoundry"
  plan_name        = "standard"
  parameters = jsonencode({
    instance_name = btp_subaccount.dev-finance.name
  })
}

# Create BAS instance
resource "btp_subaccount_entitlement" "bas" {
  subaccount_id = btp_subaccount.dev-finance.id
  service_name  = "sapappstudio"
  plan_name     = "standard-edition"
}`

**Comment by lechnerc77** [comment]
I retested the entitlement flow and had no issues with the entitlement:

```terraform
## Create managed directory
# Create a directory with ENTITLEMENT and AUTHORIZATIONS features enabled
resource "btp_directory" "dir_with_features" {
  name        = "my-feat-directory"
  description = "This is a directory with features."
  features    = ["DEFAULT", "ENTITLEMENTS", "AUTHORIZATIONS"]
}

## Add entitlement to dir
resource "btp_directory_entitlement" "bas_entitlement_dir" {
  directory_id = btp_directory.dir_with_features.id
  service_name = "sapappstudio"
  plan_name    = "standard-edition"
}

## create subaccount
resource "btp_subaccount" "my_project" {
  name       = "My Project"
  subdomain  = "my-project"
  region     = "us10"
  parent_id  = resource.btp_directory.dir_with_features.id
  depends_on = [btp_directory_entitlement.bas_entitlement_dir]
}

## Add entitlement to subaccount
resource "btp_subaccount_entitlement" "bas_entitlement_subaccount" {
  subaccount_id = btp_subaccount.my_project.id
  service_name  = "sapappstudio"
  plan_name     = "standard-edition"
}
```

Do you spot any difference wrt to entitlement of directory and subaccount to your setup?

**Comment by tcasteli** [comment]
I think the issue exists in the fact that I do not have admin rights on the global account but global account viewer. I do have Directory Administrator rights so I am able to see the entitlements and add them to the subaccount manually.

**Comment by lechnerc77** [comment]
The 403 indicates that this is an authentication issue in your specific user setup. As the assignment per se works, can you please validate that you have the right roles assigned to the user executing the Terraform script so that the actions can be executed successfully.

**Comment by tcasteli** [comment]
I am able to execute the actions by hand with this user so the right authorizations are assigned. The user has "Global account viewer" and "Directory Administrator" rights. All the other steps are being executed properly, only the adding the entitlements fails

**Comment by lechnerc77** [comment]
Is the user also assigned as Subaccount Admin? Otherwise the user won't be able to add entitlements

**Comment by tcasteli** [comment]
Yes he is subaccount admin. What I did find when listing the directory entitlements is that it states that there is no quota left:
 + "sapappstudio:standard-edition"            = {
          + category             = "APPLICATION"
          + plan_description     = "Develop applications in preconfigured dev spaces for productive development."
          + plan_display_name    = "standard-edition"
          + plan_name            = "standard-edition"
          + quota_assigned       = 2000000000
          + quota_remaining      = 0
          + service_display_name = "SAP Business Application Studio"
          + service_name         = "sapappstudio"
        }

Could that be the problem? I don't understand why there would be no more quota?

**Comment by lechnerc77** [comment]
If there is no more quota this would prevent the assignment. 

In my case the result of the data source is: 

```terraform
  "sapappstudio:standard-edition" = {
      "category" = "APPLICATION"
      "plan_description" = "Develop applications in preconfigured dev spaces for productive development."
      "plan_display_name" = "standard-edition"
      "plan_name" = "standard-edition"
      "quota_assigned" = 1
      "quota_remaining" = 1
      "service_display_name" = "SAP Business Application Studio"
      "service_name" = "sapappstudio"
    }
```

As the BAS is an application that does instance sharing, the quota makes no sense imho. 

Here a screenshot of the "Entity Assignment" in my account:

![image](https://github.com/SAP/terraform-provider-btp/assets/22294087/167f80af-d9ed-446d-9f23-9889547b7c55)

Does your setup look the same?

**Comment by lechnerc77** [comment]
I cross.-checked with another account that resembles your setup (showing unlimited assignment). This indeed gives me the the result of the data source as in your case:

```terraform
"sapappstudio:standard-edition" = {
      "category" = "APPLICATION"
      "plan_description" = "Develop applications in preconfigured dev spaces for productive development."
      "plan_display_name" = "standard-edition"
      "plan_name" = "standard-edition"
      "quota_assigned" = 2000000000
      "quota_remaining" = 0
      "service_display_name" = "SAP Business Application Studio"
      "service_name" = "sapappstudio"
    }
```

So the  ` "quota_assigned" = 2000000000` and `"quota_remaining" = 0` seem to be valid for quota assignment `unlimited`.

I applied the Terraform script from above to this subaccount and I could create the setup i.e. the entitlement without any issues (user is subaccount and directory admin, as in your setup). 

Would you mind to jump on a call to check your setup? if that i okay for you you can send me a proposal to christian.lechner@sap.com. If you find the time on short notice, I would be available today from 02:00 PM to 05:00 pm CET.

**Comment by lechnerc77** [comment]
Learnings from call:

Setup: user has the following role collections:
- Global Account **Viewer**
- Directory Admin
- Subaccount Admin

Assignment of entitlement in BTP cockpit: **works**
Assignment of entitlement via Terraform provider or BTP CLI: **fails** (HTTP code 403)

Changing setup and assigning the user the following role collections:
- Global Account **Admin**
- Directory Admin
- Subaccount Admin

Assignment of entitlement in BTP cockpit: **works**
Assignment of entitlement via Terraform provider or BTP CLI: **works**

Next step: evaluation of diff between cockpit and API calls wrt to authentication of user

**Comment by lechnerc77** [comment]
Update: confirm the observation. Same issue with BTP CLI.

Next step: Evaluate error with BTP CLI team and discuss deviation between cockpit and BTP CLI flow

Workaround: If user has the role collection "Global Account Administrator" assigned the user the deployment works.

**Comment by lechnerc77** [comment]
Addendum: the same error appears if there is no directory involved in the setup, i.e. having a subaccount directly under the global account. The role collection assignment consequently is defined as `Global Account Viewer` and `Subaccount Admin`

**Comment by lechnerc77** [comment]
@tcasteli here a short update: this issue needs some fixes down in the platform (lower level APIs). It might take a bit until these fixes are finished and finally propagated to the SAP BTP live landscape.
 
For the time being please use the workaround of assigning the role collection "Global Account Admin" to deploy your setups successfully

**Comment by tcasteli** [comment]
@lechnerc77 , thanks for the update. We'll continue with the "Global Account Admin" route for now.

**Comment by lechnerc77** [comment]
Internal reference ticket: <https://jira.tools.sap/browse/SAPBTPCFS-8784>

**Comment by lechnerc77** [comment]
The enhancement of the provider implementation also needs to take into account the `list` command needed for reading the resources as currently the deletion fails due to a timeout. This was reported in #679 
I will close #679 in favor of this ticket to have one central place of progress tracking for the enhancement wrt to the new directory logic
