### ISSUE TITLE
[BUG] can't parse the service instances list result

### ISSUE THREAD

**Issue by superwangnan** [SAP/terraform-provider-btp#567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

0.6.0-beta2

### What version of the Terraform CLI are you using?

1.6.5

### What type of issue are you facing

bug report

### Describe the bug

Hi team,
When I try to output the btp_subaccount_service_instances, I got the error as screenshot. thanks~

<img width="1102" alt="image" src="https://github.com/SAP/terraform-provider-btp/assets/20192234/e3e6b051-fc4b-4878-82f3-08c66b927e44">

**Comment by lechnerc77** [comment]
@superwangnan, I can not reproduce the error you reported. I tried the setup in a subaccount on a regular SAP landscape with:

- existing service instances  in it
- no service instances in it

Same on a SAP BTP trial account.

Can you please provide a list of the service instances that are available in your SAP BTP subaccount as this could be a service specific issue.

**Comment by lechnerc77** [comment]
Except for the `apiportal-apiaccess` I cannot find these services in the BTP service metadata (https://github.com/SAP-samples/btp-service-metadata) for services on SAP BTP, which is strange

- Is this a SAP internal system?
- Can you send me a screenshot of the service instance overview in the cockpit?

**Comment by superwangnan** [comment]
This is a trial account, please refer to the screenshot in following. apiportal-apiaccess service-plan belong to API management of integration suite.

<img width="1427" alt="image" src="https://github.com/SAP/terraform-provider-btp/assets/20192234/62ac4227-5199-456d-b902-f5cabf41223d">

**Comment by lechnerc77** [comment]
Update: Data transferred from service manager for CF service instance does not adhere to the API specification. This breaks the `unmarshal` action in the Terraform provider that relies on the generated models defined in the API given here: <https://api.sap.com/api/APIServiceManagment/resource/Service_Instances>.

This impacts the reading of single service instance entries as well as listing them
