### ISSUE TITLE
 Error: unableToCreateClient Login failed. Check your credentials. [Status: 401; Correlation ID: 6fed6f10-18b3-ba50-41e5-0fee0939bbcf]

### ISSUE THREAD

**Issue by P2007801473** [SAP/terraform-provider-btp#583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

version = "1.0.0-rc1"

### What version of the Terraform CLI are you using?

1.6.5

### What type of issue are you facing

bug report

### Describe the bug

BTP Trail is registered & same P* account is used for Github/terraform registry
BTP Trail global account has administrator access. 

provider.tf : File contents
=====================================
terraform {
  required_providers {
    btp = {
      source  = "SAP/btp"
      version = "1.0.0-rc1"
    }
  }
}
provider "btp" {
  globalaccount = "0ddf4949trial-ga"
  username = "<UserName>"
  password = "<Password>"
}
====================================
Main.tf | File contents
resource "btp_subaccount" "my_project" {
  name      = "My Project"
  subdomain = "my-project"
  region    = "us10"
}
========================================

C:\Softwares\terraform\NRD1>terraform.exe init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of sap/btp from the dependency lock file
- Using previously-installed sap/btp v1.0.0-rc1

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

C:\Softwares\terraform\NRD1>terraform.exe plan

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: unableToCreateClient
│
│   with provider["registry.terraform.io/sap/btp"],
│   on provider.tf line 11, in provider "btp":
│   11: provider "btp" {
│
│ Login failed. Check your credentials. [Status: 401; Correlation ID: 6fed6f10-18b3-ba50-41e5-0fee0939bbcf]

### Expected Behavior

terraform plan and apply commands give same error.  

### Steps To Reproduce

terraform plan or terraform apply gives error.

### User's Role Collections

subaccount administrator access provided.

### Add screenshots to help explain your problem

<img width="797" alt="TF1" src="https://github.com/SAP/terraform-provider-btp/assets/153198314/a889efd5-2651-4396-816b-8787052c5568">

### Additional context

Trail account has access, still 401 is seen.
<img width="797" alt="TF1" src="https://github.com/SAP/terraform-provider-btp/assets/153198314/a0d8c6d7-831f-4264-b016-84ac86f31097">

**Comment by P2007810156** [comment]
[P2007810156] & [P2007801473] both accounts are mine, having trouble.

**Comment by lechnerc77** [comment]
Yes but if you are using the universal ID you must adjust the settings of the Universal ID as described in SAP Note https://me.sap.com/notes/3085908 no matter if this is a S or P user. 

Closing the issue as this is not an error in the Provider but due to the wrong setup of authenticaton.

**Comment by P2007810156** [comment]
Hello, 

Please see screenshot of Universal id, I did go through sap note, from your other posts & reply. Password is fine and working for other logins. 
<img width="899" alt="SUNID" src="https://github.com/SAP/terraform-provider-btp/assets/153291475/eba1da2b-fa82-4d7c-8e7e-4d5cc6eec4f0">

**Comment by P2007810156** [comment]
From notes below steps are defined. Changed password as well.

Resolution
Use your S-user ID and S-user ID password to log on instead of your SAP Universal ID password.

In case you cannot remember your S-user account password, you can set a new one via the SAP Universal ID Account Manager as follows:

Go to the [SAP Universal ID Account Manager](https://account.sap.com/)
Log on with your SAP Universal ID credentials
Select the linked S-user ID you would like to modify
Click the pencil icon to edit the "Reset Account Password" card
Type in your new preferred account password according to the listed criteria
Repeat the same password
Click Save
Return to the application where you faced the error of invalid credentials and use the S-User ID and your newly set account password to log on.
