### ISSUE TITLE
[FEATURE (Testsetup)] Orchestrate static resources for integration tests with terraform

### ISSUE THREAD

**Issue by v0lkc** [SAP/terraform-provider-btp#59]
### What area do you want to see improved?

None

### Is your feature request related to a problem? Please describe.

All the integration test resources we use for validating datasources are currently unmanaged (in other words they have been manually created). If we'd have them managed by terraform, we could share access easier.

GlobalAccount: terraform-integration-canary
Resources to be onboarded:

- Subaccount: integration-test-acc-static
- Directory: integration-test-dir-se-static
- Directory: integration-test-dir-static
- Directory User: jenny.doe@test.com
- GlobalAccount User: jenny.doe@test.com
- Subaccount User: jenny.doe@test.com

### Describe the solution you would like

Create a terraform workspace to manage integration test resources. State shall be stored in central backend like s3 or artifactory.

**Comment by lechnerc77** [comment]
Setup of infratstucture done - see PR #532

**Comment by lechnerc77** [comment]
The abstraction of the infrastructure setup is finished. Artifactory update is available (can be used as backend)
-> Closing this issues as completed
