### ISSUE TITLE
Create Space fails due to Error: Could not find Organization with guid

### ISSUE THREAD

**Issue by P2007810156** [SAP/terraform-provider-btp#601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

version = "1.0.0-rc1"

### What version of the Terraform CLI are you using?

1.6.5

### What type of issue are you facing

regression (a behavior that used to work and stopped in a new version)

### Describe the bug

SPACE creation fails, looks for GUID, previous runs it was working fine.
# CF Spaces
resource "cloudfoundry_space" "DEV01" {
  name = "DEV01"
  org  = btp_subaccount_environment_instance.cloudfoundry.platform_id

### Expected Behavior

 org  = btp_subaccount_environment_instance.cloudfoundry.platform_id worked before for SPACE creation.

### Steps To Reproduce

main.tf file has below configuration

resource "btp_subaccount" "ksk-1319" {
  name      = "My BTP KSK1319"
  subdomain = "ksk-1319"
  region    = "us10"
}
resource "btp_subaccount_entitlement" "sapbas" {
  subaccount_id = btp_subaccount.ksk-1319.id
  service_name  = "sapappstudiotrial"
  plan_name     = "trial"
}
resource "btp_subaccount_entitlement" "alert_notification_service" {
  subaccount_id = btp_subaccount.ksk-1319.id
  service_name  = "alert-notification"
  plan_name     = "standard"
}
resource "btp_subaccount_entitlement" "contentagentservice" {
  subaccount_id = btp_subaccount.ksk-1319.id
  service_name  = "content-agent"
  plan_name     = "standard"
}
resource "btp_subaccount_entitlement" "sapbuildzone" {
  subaccount_id = btp_subaccount.ksk-1319.id
  service_name  = "build-workzone-standard"
  plan_name     = "standard"
}
resource "btp_subaccount_entitlement" "hanaservice" {
  subaccount_id = btp_subaccount.ksk-1319.id
  service_name  = "hana"
  plan_name     = "hdi-shared"
}
# Enbale CF and Create CF ORG
resource "btp_subaccount_environment_instance" "cloudfoundry" {
  subaccount_id	   = btp_subaccount.ksk-1319.id
  name             = "my-cf-environment"
  environment_type = "cloudfoundry"
  service_name     = "cloudfoundry"
  plan_name        = "standard"

  parameters = jsonencode({
    instance_name = "ksk-1319-cf"
  })
}
resource "btp_subaccount_entitlement" "build_workzone" {
  subaccount_id = btp_subaccount.ksk-1319.id
  service_name  = "SAPLaunchpad"
  plan_name     = "standard"
}
# Create app subscription to SAP Build Workzone, standard edition (depends on entitlement)
resource "btp_subaccount_subscription" "build_workzone" {
  subaccount_id = btp_subaccount.ksk-1319.id
  app_name      = "SAPLaunchpad"
  plan_name     = "standard"
  depends_on    = [btp_subaccount_entitlement.build_workzone]
}
# CF Spaces
resource "cloudfoundry_space" "DEV01" {
  name = "DEV01"
  org  = btp_subaccount_environment_instance.cloudfoundry.platform_id
}

===================
provider.tf file content. 

terraform {
  required_providers {
    btp = {
      source  = "SAP/btp"
      version = "1.0.0-rc1"
    }
	cloudfoundry = {
      source = "cloudfoundry-community/cloudfoundry"
      version = "0.51.3"
    }
  }
}

provider "btp" {
  globalaccount = "a7b33a2ctrial-ga"
  username = "username"
  password = "password"
  }
  provider "cloudfoundry" {
  api_url  = "https://api.cf.us10.hana.ondemand.com" //BTP CF API Endpoint 
  user     = "username"  //BTP Global Account Username
  password = "password"  //BTP Global Account Password
}

### User's Role Collections

subaccount administrator

### Add screenshots to help explain your problem

<img width="468" alt="SPACE01" src="https://github.com/SAP/terraform-provider-btp/assets/153291475/a68ba478-3a27-4e32-bedb-a27e9fba2056">

### Additional context

all file and details are attached.
<img width="191" alt="plan01" src="https://github.com/SAP/terraform-provider-btp/assets/153291475/77b2a25c-7a60-4122-8a25-45e44b2dcc48">

**Comment by nickels** [comment]
I can confirm the above - same behaviour is observed in my setup (version = "1.0.0-rc1").

**Comment by lechnerc77** [comment]
@P2007810156 Can you please check if the Cloud Foundry or is created in the us10 landscape or the extension landscape us10-001 or us10-002 (see also https://help.sap.com/docs/custom-domain/custom-domain-manager/extension-landscapes).

If the or is created in the extension landscape your provider config will fail. There is no way to anticipate the deployment to a specific landscape or to influence it. 
If you want to create such setup your Build pipeline needs multiple steps to handle the provider configuration.

**Comment by P2007810156** [comment]
Hello, 

Extension is not used. I did share provider.tf and main.tf files.

**Comment by lechnerc77** [comment]
@P2007810156 Can you share a screenshot of you BTP Cockpit, namely the created Cloud Foundry environment/org. This is nothing that can be seen in your Terraform files, but only is shown in the BTP Cockpit or the Terraform state file

**Comment by P2007810156** [comment]
Hello, Thanks for previous tip. 
Understood, that my CF ORG got created under us10-001, so I updated to provider file with extension, under select subaccount region us10. 

cloudfoundry_space.DEV01: Creating...
cloudfoundry_space.DEV01: Creation complete after 1s [id=3fab92e3-bf7d-4184-a65d-1f1263592da6]

Apply complete! Resources: 1 added, 0 changed, 3 destroyed.

**Comment by lechnerc77** [comment]
The only point to consider in "real life" is as mentioned that you cannot anticipate or influence the extension landscape. Hence, the static provider config might fail again.
