### ISSUE TITLE
[FEATURE] Support for User-Agent configuration via TF_APPEND_USER_AGENT env variable

### ISSUE THREAD

**Issue by sdischer-sap** [SAP/terraform-provider-btp#622]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

We are using the terraform provider to manage resources in kubernetes environment using crossplane as a framework. 
To allow a better understanding of how much our providers are being used it would be great to have a way to customize the User-Agent of any API request that is been send via the terraform provider. 

### Describe the solution you would like

The common approach in terraform seems to be to allow customizing the User-Agent by setting the env variable TF_APPEND_USER_AGENT. There are some utils implemented e.g. in the terraform cli and in the terraform-plugin-sdk to ease the access to it.
For the plugin-framework there is an open issue concerned with adding some similar utils (see https://github.com/hashicorp/terraform-plugin-framework/issues/280). The issue suggests for providers to implement something like that manually for now until there might be some more tf native utils implemented for that.

**Comment by lechnerc77** [comment]
Thanks for the feature request. We evaluate it and update the ticket accordingly. 

## Community Note

 ### Voting for Prioritization

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original post to help the community and maintainers prioritize this request.
* Please **do not** leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.

### Volunteering to Work on This Issue

* If you are interested in working on this issue, please leave a comment.
* If this would be your first contribution, please review the [contribution guide](https://github.com/SAP/terraform-provider-btp/blob/main/CONTRIBUTING.md).

**Comment by lechnerc77** [comment]
Analysis: 

- Environment variable `TF_APPEND_USER_AGENT` is not part of the documented CLI env variables (see <https://developer.hashicorp.com/terraform/cli/v1.7.x/config/environment-variables>)
- Variables was integrated in Terraform Plugin SDK, but did not make it to the Plugin Framework as mentioned in this feature request
- Enhancement of setting of header is needed in the  (provider.go)https://github.com/SAP/terraform-provider-btp/blob/main/internal/provider/provider.go#L150) to fetch the environment variable like e.g. the `BTP_USERNAME` to append the value to the custom user agent.
