### ISSUE TITLE
[BUG] Importing XSUAA Service Instance Not Possible When Setting "parameters"

### ISSUE THREAD

**Issue by andre-dossinger** [SAP/terraform-provider-btp#630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

c40cbe783b21ae494705fa0d6a76ce0e422fd4a3

### What version of the Terraform CLI are you using?

c40cbe783b21ae494705fa0d6a76ce0e422fd4a3

### What type of issue are you facing

bug report

### Describe the bug

When trying to import a XSUAA service instance after creating with parameters, the parameters attribute cannot be imported.
Aside from that it does not seem possible to update a XSUAA service instance (e.g. its name) when creating with an empty parameters JSON ({}). An attempt to do so results in a service broker error. This must be clarified with the XSUAA service owner.

### Expected Behavior

Importing of parameter attributes.

### Steps To Reproduce

1. Adjust the test "TestResourceSubaccountServiceInstance" (happy path - simple service creation with labels) to use a xsuaa with service plan application and add parameters to the resource definition.
2. Run the test: TEST_FORCE_REC=true go test ./... -run TestResourceSubaccountServiceInstance
3. The import error will come up. 

### User's Role Collections

- Subaccount Administrator

**Comment by lechnerc77** [comment]
This is probably an issue with the service manager API that is called, that does not return parameters. We made some workarounds for that (see https://github.com/SAP/terraform-provider-btp/blob/main/internal/provider/resource_subaccount_service_instance.go#L155-L157) but they will not cover import scenarios. 
We need to analyze what options we can provide here.

Side remark: intersting that the destination service did not face these issues.

**Comment by lechnerc77** [comment]
In general: The Service Manager API only returns the parameters of services that have a specific configuration in the corresponding service offering, namely the parameter `instances_retrievable` must be set to `true`. This  setting is not available for all services, especially not for all services that can be configured via dedicated parameters during creation.

Even if the service offering allows a return of the service parameters (in accordance to the description "*The configuration parameters were provided either during the creation of the instance as part of the request payload of the API: POST/v1/service_instances, or during the update of the service instance by using the API: PATCH/v1/service_instances.*") the response from the service manager does not only contain these parameters, but other data has never been specified in the creation of the update.  The relevant part of the data is stored in the JSON key `data`. There is no JSON schema available for the parameters (see <https://api.sap.com/api/APIServiceManagment/path/getServiceInstanceParameters>)

If we call the BTP CLI server with the parameter to show the parameters, the response does not return the service instance including the parameters, but just the parameters and omits all other data. Obviously the setting of the parameter `--show-parameters` leads to a call to the endpoint <https://api.sap.com/api/APIServiceManagment/path/getServiceInstanceParameters>. The expectation would be that service instance data is enriched with the parameters if this parameter is set and not that the service instance data is completely omitted.

Consequences: 

- the XSUAA service instance cannot be imported as the service offering is configured with  `instances_retrievable = false`.
- the solution proposed in the PR #666 esp. when it comes to the implementation of the `facade` does not work.

**Comment by lechnerc77** [comment]
> SAP INTERNAL: for internal error/follow-up see https://jira.tools.sap/browse/NGPBUG-375472

**Comment by lechnerc77** [comment]
Status quo:
- The BTP CLI dispatches to different endpoint if the parameter `--show-parameters` (CLI) or `parameters = true` (server) is set. Hence, we have to make at least two calls for the retrieval of the  parameters in case of an import
- The response for the call for parameters can differ depending on the service. as of now this can be a plain (but nested) JSON object that we do not know the schema or the parameters belong to the `data` key in a JSON object but as before with unknown JSON schema

As a consequence we must implement a best guess calls to the server to:
1. Fetch the basis data of the service
2. Fetch the parameters - here two calls are needed to cope with the different response schemas.  

This will only be relevant for the Import scenario and the data source for a specific service instance.
