### ISSUE TITLE
[BUG]Error when creating clients: Error creating ccv2 client: Get "/v2/info": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by dineshkumarbcs** [SAP/terraform-provider-btp#637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.0.0-rc1

### What version of the Terraform CLI are you using?

1.6.6

### What type of issue are you facing

bug report

### Describe the bug

Trying to create CF env and org space and assigning roles

### Expected Behavior

C:\Users\dines\OneDrive\Documents\Personal\BTP_AUTO\CF_Enablement>terraform plan
data.btp_subaccount_environments.all: Reading...
data.btp_subaccount_environments.all: Read complete after 1s [id=156fc11c-5bf6-4179-b10e-f942e0f2ec5c]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform planned the following actions, but then encountered a problem:

  # btp_subaccount_environment_instance.cf will be created
  + resource "btp_subaccount_environment_instance" "cf" {
      + broker_id        = (known after apply)
      + created_date     = (known after apply)
      + custom_labels    = (known after apply)
      + dashboard_url    = (known after apply)
      + description      = (known after apply)
      + environment_type = "cloudfoundry"
      + id               = (known after apply)
      + labels           = (known after apply)
      + landscape_label  = (known after apply)
      + last_modified    = (known after apply)
      + name             = "terraform-test"
      + operation        = (known after apply)
      + parameters       = jsonencode(
            {
              + instance_name = "terraform-test"
            }
        )
      + plan_id          = (known after apply)
      + plan_name        = "standard"
      + platform_id      = (known after apply)
      + service_id       = (known after apply)
      + service_name     = "cloudfoundry"
      + state            = (known after apply)
      + subaccount_id    = "156fc11c-5bf6-4179-b10e-f942"
      + tenant_id        = (known after apply)
      + type             = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/cloudfoundry-community/cloudfoundry" requires explicit configuration. Add a provider
│ block to the root module and configure the provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: Error when creating clients: Error creating ccv2 client: Get "/v2/info": unsupported protocol scheme ""
│
│   with provider["registry.terraform.io/cloudfoundry-community/cloudfoundry"],
│   on <empty> line 0:
│   (source code not available)
│

### Steps To Reproduce

End of Plan we are getting below error.
╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/cloudfoundry-community/cloudfoundry" requires explicit configuration. Add a provider
│ block to the root module and configure the provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: Error when creating clients: Error creating ccv2 client: Get "/v2/info": unsupported protocol scheme ""
│
│   with provider["registry.terraform.io/cloudfoundry-community/cloudfoundry"],
│   on <empty> line 0:
│   (source code not available)

### Add screenshots to help explain your problem

<img width="695" alt="image" src="https://github.com/SAP/terraform-provider-btp/assets/150025160/411d6082-d865-4942-affd-5790607c86d5">

**Comment by lechnerc77** [comment]
@dineshkumarbcs  the output indicated that you have a wrong configuration for the Cloud Foundry Terraform provider.  Accordingt othe error message there is no configuration at all. 
Please check that the configuration of the Cloud Foundry provider is correct and in line with the documentation given here: <https://registry.terraform.io/providers/cloudfoundry-community/cloudfoundry/latest/docs>

Be aware that there are limitation with respect to Cloud Foundry extension landscapes as discused here: <https://github.com/SAP/terraform-provider-btp/issues/601>

**Comment by dineshkumarbcs** [comment]
Thanks for the guidance.
