### ISSUE TITLE
[FEATURE] Protocol Option in BTP Subaccount Trust Config

### ISSUE THREAD

**Issue by brahammittal** [SAP/terraform-provider-btp#649]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

While doing the trust configuration with Terrafrom, default protocol is OpenID Connect. But can the Protocol option be enabled while establishing trust.

We are preferring SAML as an organization. 

### Describe the solution you would like

Enable Protocol field as input in the resource BTP_SUBACCOUNT_TRUST_CONFIGURATION

### Describe alternatives you have considered

Do it manually

**Comment by lechnerc77** [comment]
Thanks for the feature request. We evaluate it and update the issue accordingly.
            
## Community Note

### Voting for Prioritization

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original post to help the community and maintainers prioritize this request.
* Please **do not** leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.

### Volunteering to Work on This Issue

* If you are interested in working on this issue, please leave a comment.
* If this would be your first contribution, please review the [contribution guide](https://github.com/SAP/terraform-provider-btp/blob/main/CONTRIBUTING.md).

**Comment by lechnerc77** [comment]
Analysis:

- The BTP CLI commands that we rely on do not allow the setting of the protocol (OIDC, SAML) - see [btp create security/trust](https://help.sap.com/docs/btp/btp-cli-command-reference/btp-create-security-trust) and [btp update security/trust](https://help.sap.com/docs/btp/btp-cli-command-reference/btp-update-security-trust).
- To make this feature available we would need enhancements of the BTP CLI to support the `type` exposed by the platform API (see <https://api.sap.com/api/TrustConfigurationAPI/path/createIdentityProviderUsingPOST>) which support OIDC and SAML

**Comment by torsten-sap** [comment]
From the perspective of SAP Authorization and Trust Management Service we do not intend to support SAML for trust establishment in btp CLI.

The recommendation is to use Identity Authentication as identity provider and connect corporate identity providers to it, if required. See [documentation](https://help.sap.com/docs/btp/sap-business-technology-platform/establish-trust-and-federation-between-uaa-and-identity-authentication?version=Cloud):

> We recommend that you always use SAP Cloud Identity Services - Identity Authentication as single identity provider for SAP BTP. If you use corporate identity providers, connect them to your Identity Authentication tenant, which then acts as a hub. We especially recommend this if you are using multiple corporate identity providers. For platform users, the use of SAP Cloud Identity Services - Identity Authentication is mandatory.

**Comment by lechnerc77** [comment]
@torsten-sap  thanks for the clarification. 
@brahammittal : As stated by Torsten, there will be no support for SAML in context of the BTP CLI. As we rely on the BTP CLI as backend, we will not be able to support this feature. Torsten also referenced the official recommendation.
 
I will therefore close this request.
