### ISSUE TITLE
[BUG] Import of btp_subaccount_trust_configuration not possible - Unexpected Import Identifier

### ISSUE THREAD

**Issue by TVSiemens** [SAP/terraform-provider-btp#658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

v1.0.0-rc1

### What version of the Terraform CLI are you using?

1.6.6

### What type of issue are you facing

bug report

### Describe the bug

We'd like to log in to applications in a BTP subaccount only by custom IDP and deactivate the user login for sap.default.

When a new subaccount will be created, the trust configuration for the custom IDP should be done and the user login for sap.default on the just created subaccount should be deactivated.

That's why we'd like to set "available_for_user_logon" for the sap.default IDP to false.

We added the following config to our script to get the config of the sap.default IDP to change the attribute:
```
data "btp_subaccount_trust_configuration" "default" {
  subaccount_id = btp_subaccount.subaccount-dev.id
  origin        = "sap.default"
}

import {
  to = btp_subaccount_trust_configuration.default-idp
  id = data.btp_subaccount_trust_configuration.default
}
```
Unfortunately, we are getting the following error:

│ Error: Unexpected Import Identifier
│ Expected import identifier with format: subaccount_id,origin. Got: "sap.default"

### Expected Behavior

Import without errors

**Comment by TVSiemens** [comment]
Hi, thanks for the hint with the combined key, we have come one step further and the import in general works. Unfortunately, the import does not seem to work in the same run as the subaccount is created (a general terraform issue). It does not seem to be possible to create a subaccount, activate the custom IDP and deactivate the login with the default IDP in the same run.

**Comment by lechnerc77** [comment]
Hi @TVSiemens great that you could sort the import out. You are right (and I indeed forgot to mention that), that the setup you want to achieve is not feasible within in one single step but needs to be done in two sequential steps in your CI/CD setup. 
This is due to the fact that the default IdP gets created behind the scenes by the BTP and we have no way to influence that or to inject the right configuration from the start. So unfortunately nothing that can be fixed on the provider side. 

Do you face further issues or have questions. If this is not the case I would close the issue.

**Comment by TVSiemens** [comment]
Hi, we don't have other questions, case can be closed. Thanks a lot!

**Comment by TVSiemens** [comment]
Hi, deactivating the user login on sap.default works, but leads to the following error:

```
Error: Provider produced inconsistent result after apply

When applying changes to btp_subaccount_trust_configuration.default-idp, provider "provider[\"registry.terraform.io/sap/btp\"]" produced an unexpected new value:
 .identity_provider: was cty.StringVal("sap.default"), but now cty.StringVal("").
 
 This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by lechnerc77** [comment]
@TVSiemens I created a new dedicated issue for the behavior you reported to avoid mixing up things  in one issue.
