### ISSUE TITLE
[BUG] Error after Update of Trust Configuration of default IdP

### ISSUE THREAD

**Issue by lechnerc77** [SAP/terraform-provider-btp#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.0.0-rc1

### What version of the Terraform CLI are you using?

1.6.6

### What type of issue are you facing

bug report

### Describe the bug

The Terraform provider throws an error after update the trust configuration of the default IdP:

```bash
Error: Provider produced inconsistent result after apply

When applying changes to btp_subaccount_trust_configuration.default-idp, provider "provider[\"registry.terraform.io/sap/btp\"]" produced an unexpected new value:
 .identity_provider: was cty.StringVal("sap.default"), but now cty.StringVal("").
 
 This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behavior

The provider executes the update without the error i.e. updates the TF state consistently

### Steps To Reproduce

1. Create a new subaccount with a custom IdP
2. Import the SAP default IdP i.e. the trust settings  to bring it under the management of Terraform
3. Update the default IdP i.e. the trust settings  so that the custom IdP is used for the login to the subaccount

### User's Role Collections

n/a

### Additional context

Reported by @TVSiemens as follow up on question about import in #658. Created a dedicated issue for this bug to avoid mixing up questions and bugs.

**Comment by lechnerc77** [comment]
## Terraform scripts for sceanrio

### Step 1 - Creation of setup

`provider.tf`

```terraform
terraform {
  required_providers {
    btp = {
      source  = "SAP/btp"
      version = "1.0.0-rc1"
    }
  }
}

provider "btp" {
  globalaccount  = var.globalaccount
  cli_server_url = var.cli_server_url
}
```

`variables.tf`

```terraform
variable "globalaccount" {
  type = string
  default = "<SUBDOMAIN OF GLOBAL ACCOUNT>" 
}


variable "cli_server_url" {
  type    = string
  default = "https://cpcli.cf.eu10.hana.ondemand.com" 
}

variable "region" {
  type    = string
  default = "eu12"
}


`main.tf` 

``` terraform
resource "btp_subaccount" "my_project" {
  name      = "Retest IDP Issue 665"
  subdomain = "retest-idp-issue-665"
  region    = var.region
}

resource "btp_subaccount_trust_configuration" "customidp" {
  subaccount_id            = resource.btp_subaccount.my_project.id
  identity_provider        = "terraformint.accounts400.ondemand.com"
  available_for_user_logon = true
  auto_create_shadow_users = false
}
```

Execute `terraform apply`

### Step 2 - Import and update of default IdP

Change the main.tf to contain the following configuration for the import and the update 

```terraform
resource "btp_subaccount" "my_project" {
  name      = "Retest IDP Issue 665"
  subdomain = "retest-idp-issue-665"
  region    = var.region
}

resource "btp_subaccount_trust_configuration" "customidp" {
  subaccount_id            = resource.btp_subaccount.my_project.id
  identity_provider        = "terraformint.accounts400.ondemand.com"
  available_for_user_logon = true
  auto_create_shadow_users = false
}

import {
  to = btp_subaccount_trust_configuration.defaultidp
  id = "${resource.btp_subaccount.my_project.id},sap.default"
}

resource "btp_subaccount_trust_configuration" "defaultidp" {
  subaccount_id            = resource.btp_subaccount.my_project.id
  identity_provider        = ""
  auto_create_shadow_users = false
  available_for_user_logon = false
}
```

Execute `terraform apply`

**Comment by lechnerc77** [comment]
**Note** - the `terraform destroy` of the setup leads to the following warning which has no impact on the deletion of the resources and the terraform state:

```bash
Warning: SAP Default cannot be deleted
│ 
│ It is not possible to delete the trust configuration for origin 'sap.default'. Skipping the deletion
╵
```

**Comment by lechnerc77** [comment]
@TVSiemens : I tried to reproduce the issue but setup worked for me. Can you please check what is different in your scripts compared to the setup described [here](https://github.com/SAP/terraform-provider-btp/issues/665#issuecomment-1899884147).
Especially check that the imported default IdP has an empty value for the parameter `identity provider`.

**Comment by TVSiemens** [comment]
Hi @lechnerc77, with the empty value for the parameter identity provider it's working now. Thanks a lot!

**Comment by lechnerc77** [comment]
@TVSiemens : I recommend for imports of existing resources, to do a cross-check on data that is available via the corresponding data source. There are some points on SAP BTP (especially with the automatically created resources) that might look different than what I would expect them to, so this cross-check helped my a lot.
