### ISSUE TITLE
[BUG] Create Cloud Foundry Env Instance Return Error

### ISSUE THREAD

**Issue by sap-weikun** [SAP/terraform-provider-btp#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.0.0-rc2

### What version of the Terraform CLI are you using?

1.7.1

### What type of issue are you facing

bug report

### Describe the bug

When I trying to create the Cloud Foundry env instance by using the Terraform for BTP provider, sometimes I will see the created failed error regards the CF env instance status. Please kindly find my code, and the error message attach below.

```hcl
# ------------------------------------------------------------------------------------------------------
# Step 3. Create Cloudfoundry environment instance
# ------------------------------------------------------------------------------------------------------
data "btp_subaccount_environments" "all_available_env" {
  subaccount_id = btp_subaccount.btp_subaccount_terraform.id
}
resource "btp_subaccount_environment_instance" "cfmemory" {
  subaccount_id    = btp_subaccount.btp_subaccount_terraform.id
  name             = local.cf_instance_name
  environment_type = "cloudfoundry"
  service_name     = "cloudfoundry"
  plan_name        = "standard"
  landscape_label  = [for env in data.btp_subaccount_environments.all_available_env.values : env if env.service_name == "cloudfoundry" && env.environment_type == "cloudfoundry"][0].landscape_label
  parameters = jsonencode({
    instance_name = local.cf_instance_name
  })
  timeouts = {
    create = "10m"
    update = "10m"
    delete = "10m"
  }
  depends_on = [btp_subaccount.btp_subaccount_terraform]
}

# ------------------------------------------------------------------------------------------------------
# Step 4. Create Cloud Foundry space & Add User into space
# ------------------------------------------------------------------------------------------------------
data "btp_subaccount_environment_instance" "cf_env_instance_data" {
  subaccount_id = btp_subaccount.btp_subaccount_terraform.id
  id = btp_subaccount_environment_instance.cfmemory.id
}
resource "cloudfoundry_space" "dev" {
  name       = "dev"
  org        = data.btp_subaccount_environment_instance.cf_env_instance_data.platform_id
  depends_on = [btp_subaccount_environment_instance.cfmemory]
}
resource "cloudfoundry_space_users" "dev-space-users" {
  space      = cloudfoundry_space.dev.id
  managers   = [var.cloud_foundry_user_name]
  developers = [var.cloud_foundry_user_name]
  auditors   = [var.cloud_foundry_user_name]
  depends_on = [cloudfoundry_space.dev]
}

# ------------------------------------------------------------------------------------------------------
# Step 5. Create SAP AI Core Extended Service Plan & Service Key
# ------------------------------------------------------------------------------------------------------
data "cloudfoundry_service" "aicore" {
  name = "aicore"
}
data "cloudfoundry_space" "dev_space" {
  name = cloudfoundry_space.dev.name
  org = data.btp_subaccount_environment_instance.cf_env_instance_data.platform_id
}
resource "cloudfoundry_service_instance" "sap_ai_core_extended_plan_instance" {
  name         = "ai-core-extended-service-plan"
  space        = data.cloudfoundry_space.dev_space.id
  service_plan = data.cloudfoundry_service.aicore.service_plans["extended"]
}
resource "cloudfoundry_service_key" "sap_ai_core_extended_plan_instance_key" {
  name             = "key"
  service_instance = cloudfoundry_service_instance.sap_ai_core_extended_plan_instance.id
}
```

Error Message:
```hcl
│ Error: API Error Creating Resource Environment Instance (Subaccount)
│
│   with btp_subaccount_environment_instance.cfmemory,
│   on main.tf line 53, in resource "btp_subaccount_environment_instance" "cfmemory":
│   53: resource "btp_subaccount_environment_instance" "cfmemory" {
│
│ unexpected state 'UPDATING', wanted target 'OK, CREATION_FAILED'. last error: %!s(<nil>)
```

Well I do see that my cloud foundry env instance created in my BTP subaccount, but sometimes I will get the error message as above, and then the entire script executing will be show down, which cause my following script could not be executed. Could you please kindly help me and suggest how could I resolve this issue ?

Best Regards,
Weikun Liu

### Expected Behavior

Well I do see that my cloud foundry env instance created in my BTP subaccount, but sometimes I will get the error message as above, and then the entire script executing will be show down, which cause my following script could not be executed. Could you please kindly help me and suggest how could I resolve this issue ?

### Steps To Reproduce

1. Put Below code into the main.tf file
```hcl
# ------------------------------------------------------------------------------------------------------
# Define local variables for SAP BTP subaccount module
# ------------------------------------------------------------------------------------------------------
locals {
  name_suffix      = "trial"
  subaccount_name  = "Terraform"
  subdomain        = "paa-ti-sce"
  cf_instance_name = lower("cf-${local.subaccount_name}-${local.name_suffix}")
  cf_org_name      = lower("cforg-${local.subaccount_name}-${local.name_suffix}")
}

# ------------------------------------------------------------------------------------------------------
# Step 1. Create subaccount
# ------------------------------------------------------------------------------------------------------
resource "btp_subaccount" "btp_subaccount_terraform" {
  name      = local.subaccount_name
  subdomain = lower(local.subdomain)
  region    = lower(var.sap_btp_subaccount_region)
}

# ------------------------------------------------------------------------------------------------------
# Step 2. Set all entitlements in the subaccount
# ------------------------------------------------------------------------------------------------------
# Set entitlement for Cloud Foundry Runtime
resource "btp_subaccount_entitlement" "cloud_foundry_runtime" {
  subaccount_id = btp_subaccount.btp_subaccount_terraform.id
  service_name  = "APPLICATION_RUNTIME"
  plan_name     = "MEMORY"
  amount        = 1
  depends_on    = [btp_subaccount.btp_subaccount_terraform]
}
# Set entitlement for SAP AI Core - Extended Plan
resource "btp_subaccount_entitlement" "ai_core_extendend_plan" {
  subaccount_id = btp_subaccount.btp_subaccount_terraform.id
  service_name  = "aicore"
  plan_name     = "extended"
  depends_on    = [btp_subaccount.btp_subaccount_terraform]
}
# Set entitlement for SAP AI Launchpad - Subscription 
resource "btp_subaccount_entitlement" "ai_launchpad" {
  subaccount_id = btp_subaccount.btp_subaccount_terraform.id
  service_name  = "ai-launchpad"
  plan_name     = "standard"
  depends_on    = [btp_subaccount.btp_subaccount_terraform]
}

# ------------------------------------------------------------------------------------------------------
# Step 3. Create Cloudfoundry environment instance
# ------------------------------------------------------------------------------------------------------
data "btp_subaccount_environments" "all_available_env" {
  subaccount_id = btp_subaccount.btp_subaccount_terraform.id
}
resource "btp_subaccount_environment_instance" "cfmemory" {
  subaccount_id    = btp_subaccount.btp_subaccount_terraform.id
  name             = local.cf_instance_name
  environment_type = "cloudfoundry"
  service_name     = "cloudfoundry"
  plan_name        = "standard"
  landscape_label  = [for env in data.btp_subaccount_environments.all_available_env.values : env if env.service_name == "cloudfoundry" && env.environment_type == "cloudfoundry"][0].landscape_label
  parameters = jsonencode({
    instance_name = local.cf_instance_name
  })
  timeouts = {
    create = "10m"
    update = "10m"
    delete = "10m"
  }
  depends_on = [btp_subaccount.btp_subaccount_terraform]
}

# ------------------------------------------------------------------------------------------------------
# Step 4. Create Cloud Foundry space & Add User into space
# ------------------------------------------------------------------------------------------------------
data "btp_subaccount_environment_instance" "cf_env_instance_data" {
  subaccount_id = btp_subaccount.btp_subaccount_terraform.id
  id = btp_subaccount_environment_instance.cfmemory.id
}
resource "cloudfoundry_space" "dev" {
  name       = "dev"
  org        = data.btp_subaccount_environment_instance.cf_env_instance_data.platform_id
  depends_on = [btp_subaccount_environment_instance.cfmemory]
}
resource "cloudfoundry_space_users" "dev-space-users" {
  space      = cloudfoundry_space.dev.id
  managers   = [var.cloud_foundry_user_name]
  developers = [var.cloud_foundry_user_name]
  auditors   = [var.cloud_foundry_user_name]
  depends_on = [cloudfoundry_space.dev]
}

# ------------------------------------------------------------------------------------------------------
# Step 5. Create SAP AI Core Extended Service Plan & Service Key
# ------------------------------------------------------------------------------------------------------
data "cloudfoundry_service" "aicore" {
  name = "aicore"
}
data "cloudfoundry_space" "dev_space" {
  name = cloudfoundry_space.dev.name
  org = data.btp_subaccount_environment_instance.cf_env_instance_data.platform_id
}
resource "cloudfoundry_service_instance" "sap_ai_core_extended_plan_instance" {
  name         = "ai-core-extended-service-plan"
  space        = data.cloudfoundry_space.dev_space.id
  service_plan = data.cloudfoundry_service.aicore.service_plans["extended"]
}
resource "cloudfoundry_service_key" "sap_ai_core_extended_plan_instance_key" {
  name             = "key"
  service_instance = cloudfoundry_service_instance.sap_ai_core_extended_plan_instance.id
}
```

2. Maintain below variables in **variable.tf** file
```hcl
variable "sap_btp_global_account_id" {

  description = "SAP BTP Global Account ID"
  type        = string
  default     = ""
}

variable "sap_btp_subaccount_region" {

  description = "SAP BTP Subaccount Region"
  type        = string
}

variable "sap_btp_user_name" {

  description = "SAP BTP Global Account Admin User Name"
  type        = string
  default     = ""
}

variable "sap_btp_user_password" {

  description = "SAP BTP Global Account Admin User Password"
  type        = string
  default     = ""
}

variable "cloud_foundry_region" {

  description = "The Region of Cloud Foundry Env will be Created"
  type        = string
  default     = "us10-001"
}

variable "cloud_foundry_user_name" {

  description = "Cloud Foundry Admin User Name"
  type        = string
}

variable "cloud_foundry_user_password" {

  description = "Cloud Foundry Admin User Password"
  type        = string
}
```

3. Maintain below values in the **terraform.tfvars** file
```hcl
# Define SAP BTP Global Account User Credentials
sap_btp_global_account_id = 
sap_btp_subaccount_region = 
sap_btp_user_name = ""
sap_btp_user_password = 

# Define Cloud Foundry Env Variables
cloud_foundry_region = 
cloud_foundry_user_name = 
cloud_foundry_user_password = 
```

4. execute **terraform apply**, and then execute **terraform apply -auto-approve**

### User's Role Collections

N/A

### Additional context

N/A

**Comment by lechnerc77** [comment]
@sap-weikun I think you should add a `depends on` for the CF environment resource, namely a depends on to the `resource "btp_subaccount_entitlement" "cloud_foundry_runtime" `. The CF environment depends on the entitlement to be successfully assigned. 

Some general remarks on your setup:

- You only need a `depends on` if Terraform cannot determine the dependency implictly e.g. due to referencing the ID of a resource. So severeal `depend_on` statements could be removed from your congiguration.
- Your CF setup only works in regions that do not have a CF extension landscape as then you will not be able to authenticate against the right CF endpoint for the Cloud Foundry provider.
- I would also recommend to add a `time_sleep` resource (see https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep) before creating service instances in CF. The entitlement needs to be propagated to the CF marketplace. This might take a bit. Otherwise you might run into errors stating that the entitled service does not exist in CF.

**Comment by sap-weikun** [comment]
> @sap-weikun I think you should add a `depends on` for the CF environment resource, namely a depends on to the `resource "btp_subaccount_entitlement" "cloud_foundry_runtime" `. The CF environment depends on the entitlement to be successfully assigned.
> 
> Some general remarks on your setup:
> 
> * You only need a `depends on` if Terraform cannot determine the dependency implictly e.g. due to referencing the ID of a resource. So severeal `depend_on` statements could be removed from your congiguration.
> * Your CF setup only works in regions that do not have a CF extension landscape as then you will not be able to authenticate against the right CF endpoint for the Cloud Foundry provider.
> * I would also recommend to add a `time_sleep` resource (see https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep) before creating service instances in CF. The entitlement needs to be propagated to the CF marketplace. This might take a bit. Otherwise you might run into errors stating that the entitled service does not exist in CF.

@lechnerc77 Thank you so so much for your reply. Yes adding dependencies in the create cloud foundry env instance block resolved the issue for sure.

In your reply you are saying "**Your CF setup only works in regions that do not have a CF extension landscape as then you will not be able to authenticate against the right CF endpoint for the Cloud Foundry provider.**"

I do see the error of "**You are not authorized to perform the requested action**" when I'm trying to create the AI Core service instance after the cloud foundry env instance and space created successfully. I'm also seeing that I have the Org Manager role and also the Space Manager roles after the TF scripts executed. 

As you can see in my code that I shared previously, I'm using the **TF Cloud Foundry provider**, resource **cloudfoundry_service_instance** to create the service instance in the cloud foundry space. 

So my question would be:
1. Is this a correct way of creating the service instance in the CF space ? Since I'm seeing TF BTP Provider could not perform the task on the CF space level.
2. Should I switch to use BTP provider to create the service instance? 
3. If I do so, is it still possible for me to create the service key?

I'm pretty new to this Terraform and I'm really appreciate for your insight here

Best Regards,
Weikun Liu

**Comment by lechnerc77** [comment]
@sap-weikun The error you are seeing is not caused by the scenario I mentioned as you could authenticate but ran into an authorization issue. 

This seems to be a service specific issue. To pin down the issue you should first try if you can create the service instance in the BTP cockpit. If this is not possible the overall setup is not correct. I went over the documentation:

- The subaccount should be created with the `used_for_production` flag set,  see <https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/create-subaccount>
- The user must also have the space developer and space auditor role assigned, see <https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/create-space> 

It could also be that the entitlement was not propagated to the CF Marketplace. Does the execution also fail if you execute again after the first error? If this is the case then you need to introduce the `time_sleep` resource before creating the service instance. Usually 30 seconds are sufficient. 

I just checked, but it seems that you can also create the service instance without any runtime, although this is not documented. So you can also give the Terraform provider for BTP a try to create the service instance (https://registry.terraform.io/providers/SAP/btp/latest/docs/resources/subaccount_service_instance) and then create a service key/binding (https://registry.terraform.io/providers/SAP/btp/latest/docs/resources/subaccount_service_binding).

**Comment by sap-weikun** [comment]
@lechnerc77 
Thank you so much for your reply again. I just tried to add the time_sleep for 30 secs between assign CF space level role and create BTP service instance under the CF space, and this works for me. So that I think the BTP service instance could be created in the BTP subaccount marked for non-prod usage, but we must wait a little bit after assign the CF space level role, it will take sometimes to reflected in the CF env. 

And also I'm seeing that in-order to create the CF env instance in the SAP BTP successfully, we must added the parameter **landscape_label**, otherwise the creation will failed. 

I'm using terraform for BTP provider version 1.0.0-rc2 but in the [documentation](https://registry.terraform.io/providers/SAP/btp/latest/docs/resources/subaccount_environment_instance) I'm not seeing this parameter documented. The explanation in this doc is pretty clear but from my side I think it is clear and understandable after the user running into this issue. I think it would be better to documented this parameter and explicit show this parameter, so that the beginner like me could have a clear picture when writing the configuration HCL.

Best Regards,
Weikun Liu

**Comment by lechnerc77** [comment]
@sap-weikun Thanks for the feedback. We will improve the documentation accordingly and add the parameter to the example for Cloud Foundry in the `resource_subaccount_environment_instance`. I created #692 to follow-up on this.
