### ISSUE TITLE
[FEATURE] Managing API Credentials for Calling REST APIs of SAP Authorization and Trust Management Service

### ISSUE THREAD

**Issue by CHERIANS** [SAP/terraform-provider-btp#689]
BTP CLI Server supports [Managing API Credentials for Calling REST APIs of SAP Authorization and Trust Management Service](https://help.sap.com/docs/btp/sap-business-technology-platform/managing-api-credentials-for-calling-rest-apis-of-sap-authorization-and-trust-management-service?locale=en-US&version=Cloud). Implement support for

- [ ] Create API credentials
- [ ] Show all API credentials
- [ ] Show details about specific API credentials
- [ ] Delete API credentials

**Comment by lechnerc77** [comment]
SAP-internal: Dependency to https://jira.tools.sap/browse/XSUAA-4128 for Swagger file needed for model generation

**Comment by lechnerc77** [comment]
Update: The Swagger file is now available ( SAP Internal access only: https://xsuaa-provisioning-sb.cf.stagingaws.hanavlab.ondemand.com/swagger-ui/index.html?urls.primaryName=Platform%20API) containing the schema information. 

The resource for the API credentials and especially the models used for the interaction with the CLI backend can now be generated

**Comment by diya-dhan** [comment]
Swagger Definition: https://xsuaa-provisioning-sb.cf.stagingaws.hanavlab.ondemand.com/swagger-ui/index.html?urls.primaryName=Platform%20API

**Comment by diya-dhan** [comment]
If after navigating to the above mentioned link, the below page opens up
<img width="1464" alt="image" src="https://github.com/SAP/terraform-provider-btp/assets/77057240/ac662146-7b77-4730-b01e-e0de312279fd">

The right page can be found by choosing ***Platform API*** from the ***Select a definition*** dropdown.
<img width="594" alt="image" src="https://github.com/SAP/terraform-provider-btp/assets/77057240/1f08941e-f0ac-488b-b5bc-82b17902e86c">

**Comment by vipinvkmenon** [comment]
SAP-Internal: Dependency to https://jira.tools.sap/browse/XSUAA-4315 to be resolved

**Comment by sdischer-sap** [comment]
@CHERIANS 
Do we have a timeline for that feature to be released? 
Having this would be highly beneficial for the btp crossplane provider on our end.

**Comment by diya-dhan** [comment]
Dependency to https://jira.tools.sap/browse/XSUAA-4398 to be resolved

**Comment by vipinvkmenon** [comment]
Dependency on https://jira.tools.sap/browse/XSUAA-4398

**Comment by v0lkc** [comment]
Do you have any objections if we start implementing this as beta resource and don't wait for XSUAA-4398 to be resolved? Meaning the code would make it to the repository, but the resource itself would not become active to end users for the time being.

**Comment by lechnerc77** [comment]
@v0lkc The implementation is already going on. But imho it makes no sense to push a resource that has known errors into a release even as beta. Especially as no external customer up to now  has requested this feature.
