### ISSUE TITLE
[FEATURE] add timeout block to resources

### ISSUE THREAD

**Issue by m1madness** [SAP/terraform-provider-btp#702]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

Hello,

could you please add customisable timeouts to the resources.  BTP might take longer in regions far away. Mumbai from europe timeouts for me on the regular.

Kind regards,
M

### Describe the solution you would like

[Here](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts) is a guide how you could implement the timeouts.

**Comment by lechnerc77** [comment]
@m1madness Besides the default value of 10 minutes, we already support customizable timeout blocks for some resources like service instances and environment instance. Can you please elaborate more which resources are causing your issues that are not yet covered with the timeout blocks and where 10 minutes are not sufficient..
