### ISSUE TITLE
[BUG] Failure in entitlements process

### ISSUE THREAD

**Issue by MatanElitzur** [SAP/terraform-provider-btp#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.0.0

### What version of the Terraform CLI are you using?

1.5.7

### What type of issue are you facing

bug report

### Describe the bug

There are errors in the entitlements process
In the beginning, I had 2 resources for the entitlements, one for shared and the other for amount.
I tried to reduce the number of entitlements for each resource up to 9 and also to change the terraform code to work with dependencies, but still, the code failed.
[Erros Log](https://github.wdf.sap.corp/Portal-CF/terraform_dev/blob/main/portal-devops-ci_Devops%20CI%20Sub_eu12/terraformResult.txt)
 
[TerraformFile](https://github.wdf.sap.corp/Portal-CF/terraform_dev/blob/main/modules/common/main.tf)
[entitlements_file](https://github.wdf.sap.corp/Portal-CF/terraform_dev/blob/main/modules/common/entitlements.tf  )

### Expected Behavior

The expected behavior is that I will have only 2 entitlements resources like before 
[Entitlements_before](https://github.wdf.sap.corp/Portal-CF/terraform_dev/blob/e679429d7ef8cd09b66c4e21223a81a90035a4f7/modules/common/entitlements.tf)
and that the process will end successfully

### Steps To Reproduce

1. you can use the entitlements from [Entitlements](https://github.wdf.sap.corp/Portal-CF/terraform_dev/blob/e679429d7ef8cd09b66c4e21223a81a90035a4f7/modules/common/entitlements.tf)
2. You can use the two entitlements resources from here [Terraform_code](https://github.wdf.sap.corp/Portal-CF/terraform_dev/blob/e1927cf1d4451de7cd9d8e7d8d270e7eb812ea3f/modules/common/main.tf)

### User's Role Collections

- Subaccount Viewer
- Subaccount Administrator
- Subaccount Service Administrator

**Comment by MatanElitzur** [comment]
I can give you permission to [subaccount](https://canary.cockpit.btp.int.sap/cockpit/#/globalaccount/4e8b49a2-b2dd-44b7-b877-1bace45078af/subaccount/6005cfb7-5829-4507-8f6f-46fd9f5eb7e7/subaccountoverview)

**Comment by lechnerc77** [comment]
Trying to reproduce the issue on a BTP life  landscape using the following setup:

*variables.tf*

```terraform
###
# Entitlements - that needs to configure with amount
# Count: 12
###
variable "entitlements_amount" {
  description = "List of entitlements defined with amount for a BTP subaccount"
  type = list(object({
    description = string
    name        = string
    plan        = string
    amount      = number
  }))

  default = [
    {
      description = "Application Logging Service"
      name        = "application-logs"
      plan        = "standard"
      amount      = 1
    },
    {
      description = "Cloud Foundry Runtime"
      name        = "APPLICATION_RUNTIME"
      plan        = "MEMORY"
      amount      = 2
    },
    {
      description = "auditlog"
      name        = "auditlog"
      plan        = "standard"
      amount      = 1
    },
    {
      description = "auditlog"
      name        = "auditlog"
      plan        = "oauth2"
      amount      = 1
    },
    {
      description = "Credential Store"
      name        = "credstore"
      plan        = "standard"
      amount      = 1
    },
    {
      description = "ABAP Environment"
      name        = "abap"
      plan        = "abap_compute_unit"
      amount      = 1
    },
    {
      description = "ABAP Environment"
      name        = "abap"
      plan        = "hana_compute_unit"
      amount      = 1
    },
    {
      description = "ABAP Solution"
      name        = "abap-solution"
      plan        = "standard"
      amount      = 1
    },
    {
      description = "Custom Domain Service"
      name        = "custom-domain-manager"
      plan        = "standard"
      amount      = 1
    },
    {
      description = "Application Autoscaler"
      name        = "autoscaler"
      plan        = "lite"
      amount      = 2
    },
    {
      description = "Cloud Logging"
      name        = "cloud-logging"
      plan        = "standard"
      amount      = 1
    },
    {
      description = "Kyma Runtime"
      name        = "kymaruntime"
      plan        = "aws"
      amount      = 1
    }

  ]
}

###
# Entitlements shared units, not need to set an amount
# Count: 18
###
variable "entitlements_shared_units" {
  description = "List of entitlements shared units for a BTP subaccount"
  type = list(object({
    description = string
    name        = string
    plan        = string
  }))

  default = [
    {
      description = "Cloud Portal Service"
      name        = "PortalApplication"
      plan        = "standard"
    },
    {
      description = "Cloud Portal Service (Application)"
      name        = "portal"
      plan        = "standard"
    },
    {
      description = "Connectivity Service"
      name        = "connectivity"
      plan        = "lite"
    },
    {
      description = "SAP Content Agent Service"
      name        = "content-agent"
      plan        = "application"
    },
    {
      description = "Destination Service"
      name        = "destination"
      plan        = "lite"
    },
    {
      description = "Feature Flags"
      name        = "feature-flags-dashboard"
      plan        = "dashboard"
    },
    {
      description = "Feature Flags"
      name        = "feature-flags"
      plan        = "standard"
    },
    {
      description = "Feature Flags"
      name        = "feature-flags"
      plan        = "lite"
    },
    {
      description = "HTML5 Application Repository Service"
      name        = "html5-apps-repo"
      plan        = "app-host"
    },
    {
      description = "HTML5 Application Repository Service"
      name        = "html5-apps-repo"
      plan        = "app-runtime"
    },
    {
      description = "SAP Malware Scanning Service"
      name        = "malware-scanner"
      plan        = "clamav"
    },
    {
      description = "SAP Business Application Studio"
      name        = "sapappstudio"
      plan        = "standard-edition"
    },
    {
      description = "SAP Build Work Zone, standard edition"
      name        = "SAPLaunchpad"
      plan        = "standard"
    },
    {
      description = "SAP Content Agent Service"
      name        = "content-agent"
      plan        = "standard"
    },
    {
      description = "Cloud Portal Service"
      name        = "portal"
      plan        = "standard"
    },
    {
      description = "SAP HANA Cloud"
      name        = "hana-cloud"
      plan        = "hana"
    },
    {
      description = "SAP HANA Schemas & HDI Containers"
      name        = "hana"
      plan        = "hdi-shared"
    },
    {
      description = "Alert Notification"
      name        = "alert-notification"
      plan        = "standard"
    }
  ]
}
```

*main.tf*

```terraform
## create subaccount
resource "btp_subaccount" "my_project" {
  name      = "Subbacount Retest 537"
  subdomain = "my-subaccount-retest537"
  region    = "us10"
}



## Add entitlement to subaccount with amount
resource "btp_subaccount_entitlement" "entitlements" {
  for_each = {
    for index, entitlement in var.entitlements_amount :
    index => entitlement
  }

  amount        = each.value.amount
  plan_name     = each.value.plan
  service_name  = each.value.name
  subaccount_id = btp_subaccount.my_project.id
}


resource "btp_subaccount_entitlement" "entitlements_shared_units" {
  for_each = {
    for index, entitlement in var.entitlements_shared_units :
    index => entitlement
  }

  plan_name     = each.value.plan
  service_name  = each.value.name
  subaccount_id = btp_subaccount.my_project.id
}
```

Count: 12 entitlements with amount; 18 entitlements without amount

**Result**: Creation of subaccount with entitlements was successful. Execution happened in parallel to check for throttling issues

**Comment by lechnerc77** [comment]
@MatanElitzur : Currently error is not reproducible. Does the error occur with specific service/service plan combinations? If yes can you please add the corresponding service and plan combinations that cause the error.

After an error, does a subsequent execution of `terraform apply` fix the issue?

**Comment by MatanElitzur** [comment]
> @MatanElitzur : Currently error is not reproducible. Does the error occur with specific service/service plan combinations? If yes can you please add the corresponding service and plan combinations that cause the error.
> 
> After an error, does a subsequent execution of `terraform apply` fix the issue?

I will try to find the problematic service

**Comment by MatanElitzur** [comment]
This is the first problematic
    {
      group  = "UI5 Flexibility Design and Configuration"
      name   = "ui5-flexibility-design-and-configuration"
      plan   = "design-and-configuration"
      amount = 3
    },

**Comment by MatanElitzur** [comment]
> Adjusted the variable `entitlements_amount` according to problematic services. The updated `variables.tf` file looks like this:
> 
> ```terraform
> ###
> # Entitlements - that needs to configure with amount
> # Count: 14
> ###
> variable "entitlements_amount" {
>   description = "List of entitlements defined with amount for a BTP subaccount"
>   type = list(object({
>     description = string
>     name        = string
>     plan        = string
>     amount      = number
>   }))
> 
>   default = [
>     {
>       description = "Application Logging Service"
>       name        = "application-logs"
>       plan        = "standard"
>       amount      = 1
>     },
>     {
>       description = "Cloud Foundry Runtime"
>       name        = "APPLICATION_RUNTIME"
>       plan        = "MEMORY"
>       amount      = 2
>     },
>     {
>       description = "auditlog"
>       name        = "auditlog"
>       plan        = "standard"
>       amount      = 1
>     },
>     {
>       description = "auditlog"
>       name        = "auditlog"
>       plan        = "oauth2"
>       amount      = 1
>     },
>     {
>       description = "Credential Store"
>       name        = "credstore"
>       plan        = "standard"
>       amount      = 1
>     },
>     {
>       description = "ABAP Environment"
>       name        = "abap"
>       plan        = "abap_compute_unit"
>       amount      = 1
>     },
>     {
>       description = "ABAP Environment"
>       name        = "abap"
>       plan        = "hana_compute_unit"
>       amount      = 1
>     },
>     {
>       description = "ABAP Solution"
>       name        = "abap-solution"
>       plan        = "standard"
>       amount      = 1
>     },
>     {
>       description = "Custom Domain Service"
>       name        = "custom-domain-manager"
>       plan        = "standard"
>       amount      = 1
>     },
>     {
>       description = "Application Autoscaler"
>       name        = "autoscaler"
>       plan        = "lite"
>       amount      = 2
>     },
>     {
>       description = "Cloud Logging"
>       name        = "cloud-logging"
>       plan        = "standard"
>       amount      = 1
>     },
>     {
>       description = "Kyma Runtime"
>       name        = "kymaruntime"
>       plan        = "aws"
>       amount      = 1
>     },
>     {
>       description = "Mobile Services"
>       name        = "mobile-services"
>       plan        = "standard"
>       amount      = 1
>     },
>     {
>       description = "UI5 Flexibility Design and Configuration"
>       name        = "ui5-flexibility-design-and-configuration"
>       plan        = "design-and-configuration"
>       amount      = 1
>     }
>   ]
> }
> 
> 
> ###
> # Entitlements shared units, not need to set an amount
> # Count: 18
> ###
> variable "entitlements_shared_units" {
>   description = "List of entitlements shared units for a BTP subaccount"
>   type = list(object({
>     description = string
>     name        = string
>     plan        = string
>   }))
> 
>   default = [
>     {
>       description = "Cloud Portal Service"
>       name        = "PortalApplication"
>       plan        = "standard"
>     },
>     {
>       description = "Cloud Portal Service (Application)"
>       name        = "portal"
>       plan        = "standard"
>     },
>     {
>       description = "Connectivity Service"
>       name        = "connectivity"
>       plan        = "lite"
>     },
>     {
>       description = "SAP Content Agent Service"
>       name        = "content-agent"
>       plan        = "application"
>     },
>     {
>       description = "Destination Service"
>       name        = "destination"
>       plan        = "lite"
>     },
>     {
>       description = "Feature Flags"
>       name        = "feature-flags-dashboard"
>       plan        = "dashboard"
>     },
>     {
>       description = "Feature Flags"
>       name        = "feature-flags"
>       plan        = "standard"
>     },
>     {
>       description = "Feature Flags"
>       name        = "feature-flags"
>       plan        = "lite"
>     },
>     {
>       description = "HTML5 Application Repository Service"
>       name        = "html5-apps-repo"
>       plan        = "app-host"
>     },
>     {
>       description = "HTML5 Application Repository Service"
>       name        = "html5-apps-repo"
>       plan        = "app-runtime"
>     },
>     {
>       description = "SAP Malware Scanning Service"
>       name        = "malware-scanner"
>       plan        = "clamav"
>     },
>     {
>       description = "SAP Business Application Studio"
>       name        = "sapappstudio"
>       plan        = "standard-edition"
>     },
>     {
>       description = "SAP Build Work Zone, standard edition"
>       name        = "SAPLaunchpad"
>       plan        = "standard"
>     },
>     {
>       description = "SAP Content Agent Service"
>       name        = "content-agent"
>       plan        = "standard"
>     },
>     {
>       description = "Cloud Portal Service"
>       name        = "portal"
>       plan        = "standard"
>     },
>     {
>       description = "SAP HANA Cloud"
>       name        = "hana-cloud"
>       plan        = "hana"
>     },
>     {
>       description = "SAP HANA Schemas & HDI Containers"
>       name        = "hana"
>       plan        = "hdi-shared"
>     },
>     {
>       description = "Alert Notification"
>       name        = "alert-notification"
>       plan        = "standard"
>     }
>   ]
> }
> ```
> 
> I executed the following retest setups:
> 
> Scenario	Expected Result	Result after application
> Entitlement of the two problematic services only	The two entitlements are added successfully	✅
> Entitlement of type `entitlements_amount` only including problematic services	All 14 entitlements are added successfully	✅
> Entitlement of all types (`entitlements_amount` + `entitlements_shared_units`)	All 32 entitlements are added successfully	✅

Hi @lechnerc77 
what about if you will add another entitlement or add quota to a not problematic service and update the subaccount
Does this scenario pass as well?

**Comment by lechnerc77** [comment]
@MatanElitzur 

Retest: 

1. Create a subaccount with 14 entitlements
2. Update subaccount with one additional new entitlement and changed quota of an entitlement from step 1.

Result: New entitlement is created and quota is updated successfully

> Remark: As the loop is index based, new entitlements must be added at the end of the array defined in the variables as otherwise unwanted deletion and re-creations might occur.

I close this issue as non reproduceable as the create in parallel as well as updates work. Deletion also can be executed successfully.
