### ISSUE TITLE
[FEATURE] subaccounts shall be movable

### ISSUE THREAD

**Issue by v0lkc** [SAP/terraform-provider-btp#72]
### What area do you want to see improved?

None

### Is your feature request related to a problem? Please describe.

So far we don't support moving directories and subaccounts. In other words, terraform would try to recreate the subaccount or directory in case someone updates the `parent_id`. 

```hcl
resource "btp_subaccount" "a_subaccount" {
  parent_id = "" # can be the id of a directory or globalaccount
}

resource "btp_directory" "a_directory" {
  parent_id = "" #  can be the id of a directory or globalaccount
}
```

### Describe the solution you would like

Terraform shall move the subaccount/directory to the given directory or globalaccount specified by the `parent_Id`.

**Comment by lechnerc77** [comment]
Only Subaccounts support a `move` command. See BTP CLI documentation:

- <https://help.sap.com/docs/btp/btp-cli-command-reference/btp-move-accounts-subaccount>

**Comment by lechnerc77** [comment]
Waiting for customer feedback if this feature is really needed in Terraform scenarios. Putting it out-of-scope for the time being.

**Comment by lechnerc77** [comment]
The "move" is an imperative statement that is restricted to CLI use cases (especially when moving to feature set B and migrating to directories . The move is not needed in a declarative setup i.e. needs to be solved differently if needed. 

Closing this issue
