### ISSUE TITLE
[FEATURE] Add action to validate provider against key test-samples

### ISSUE THREAD

**Issue by vipinvkmenon** [SAP/terraform-provider-btp#723]
### What area do you want to see improved?

other

### Is your feature request related to a problem? Please describe.

Introduce a GH action that runs the terraform provider against some of the popular scenarios from the [SAP-samples](https://github.com/SAP-samples/btp-terraform-samples) repository.
Why
- A confidence in the compatibility and stability of the provider against some common scenarios
- Wider coverage of resources used in different ways
- Updated scenarios over time 

### Describe the solution you would like

A gh action that can be merged to the existing integration action or a separate action `scenario-test` which clones the samples repo and them on a given GlobalAccount.
The action should be configurable to select specific folders/scenarios.
For E.G [discovery-center](https://github.com/SAP-samples/btp-terraform-samples/tree/main/released). And many other folder as configured.

**Comment by lechnerc77** [comment]
@vipinvkmenon This would mean that we from the Terraform provider side would validate the missions if they are semantically correct. This is something I would oppose to implementing the provider scenario. If such a test should be executed, it should be implemented in the samples repository fetching a stable version of the provider and validating that the emissions can be executed. If and only if this is safeguarded based on the samples with a clear responsibility to fix the issues on the mission owner side, they could be fetched from the provider and can be executed via the unpublished/locally built provider.

**Comment by lechnerc77** [comment]
PR with setup is available and merged: https://github.com/SAP-samples/btp-terraform-samples/pull/122
