### ISSUE TITLE
[BUG] docs/resources/subaccount_environment_instance.md 

### ISSUE THREAD

**Issue by piotrmiskiewicz** [SAP/terraform-provider-btp#742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

-

### What version of the Terraform CLI are you using?

-

### What type of issue are you facing

bug report

### Describe the bug

The example in the file `docs/resources/subaccount_environment_instance.md` contains wrong Kyma parameters, for example auto_scaler_min but should be camel case autoScalerMin.
It was introduced by a commit: https://github.com/SAP/terraform-provider-btp/commit/bb15bb76bb5e6ee0c352fdc3367679b0b82d1918

See: https://help.sap.com/docs/btp/sap-business-technology-platform/provisioning-and-update-parameters-in-kyma-environment?locale=en-US

### Expected Behavior

Correct parameters in the example

**Comment by vipinvkmenon** [comment]
Will be looked into
