### ISSUE TITLE
[FEATURE] Integration with SAP Cloud ALM

### ISSUE THREAD

**Issue by lechnerc77** [SAP/terraform-provider-btp#747]
### What area do you want to see improved?

other

### Is your feature request related to a problem? Please describe.

The Terraform provider can be used for governance aspects especially drift detection of configuration. Therefore there should be an option to integrate with SAP Cloud ALM to align or enhance the existing governance workflows in SAP CALM with results from a drift detection.

Bonus would be to execute the drift detection in an integrated fashion, but this could be a second step

### Describe the solution you would like

See description

### Describe alternatives you have considered

Could be realized outside of SAP ALM, but then governance processes must be setup twice

### Additional context

n/a

**Comment by drvup** [comment]
Sounds like a good idea! Looking forward for it :)

**Comment by lechnerc77** [comment]
After discussion with CALM team there are no plans of CALM to integrate Terraform into their monitoring setup.
If you want to influence CALM development topics and would like to see this integration, please open a influence request via the [SAP customer influence program](https://influence.sap.com/) to address the CALM development directly.
