### ISSUE TITLE
[FEATURE] Document assumed/prerequisite permissions

### ISSUE THREAD

**Issue by SeanKilleen** [SAP/terraform-provider-btp#759]
### What area do you want to see improved?

documentation

### Is your feature request related to a problem? Please describe.

I'm attempting to share our terraform with newer team members so that they can apply changes as well. I have a higher degree of permissions in our system than they do. When I apply Terraform it succeeds; when they apply it, they see a 403 Forbidden error.

As I troubleshoot each of those, I'm not sure if I can specify granular permissions, or if this provider assumes that the user executing the Terraform is the admin of the global account. 

I may end up needing to move to a GitOps based solution in order to allow colleagues to apply the Terraform, but I'd love to avoid that if I could (without granting them a large swath of admin permissions).

### Describe the solution you would like

A note in the README about baseline permissions. Even better would be notes in the Terraform provider docs on a per-resource basis. I'd be happy to help with this once I understand the information a bit more.

**Comment by lechnerc77** [comment]
@SeanKilleen Thanks for the request. The Terraform provider and the services called underneath validate the role collections your user (or technical user) has assigned. Depending on what you are doing you need different roles collections or you might want to restrict the role collections your user has assigned. In addition is you e.g., create a subaccount via Terraform, the user executing the script automatically gets the `subaccount administrator` role collection assigned

I assume you would like to see the following information in the documentation:  what is the *least* privilege (namely role collection) a user needs to have in roder to be able to be able to handle resource xyz via Terraform. Is my understanding correct?

**Comment by SeanKilleen** [comment]
@lechnerc77 sorry I missed your question on this previously but yes, that's a great step forward, and I thank you for it!
