### ISSUE TITLE
[BUG] tfdocs-plugin removes links

### ISSUE THREAD

**Issue by lechnerc77** [SAP/terraform-provider-btp#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.2.0

### What version of the Terraform CLI are you using?

1.7.3

### What type of issue are you facing

bug report

### Describe the bug

The temporary workaround of pinning the version for the tfplugin-docs in the `main.go` must be removed after fix of issue <https://github.com/hashicorp/terraform-plugin-docs/issues/355>.

This is a follow-up issue for PR #773

### Expected Behavior

n/a

### Steps To Reproduce

see <https://github.com/hashicorp/terraform-plugin-docs/issues/355>

### User's Role Collections

n/a

### Add screenshots to help explain your problem

n/a

### Additional context

n/a

**Comment by vipinvkmenon** [comment]
ToDo: Track i[ssue-355](https://github.com/hashicorp/terraform-plugin-docs/issues/355) of tf-plugin-docs
