### ISSUE TITLE
[INTERNAL] Add action to validate provider against key test-samples in internal landscape

### ISSUE THREAD

**Issue by CHERIANS** [SAP/terraform-provider-btp#776]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

Need a mechanism to warn if there are upcoming changes in any of the API's

### Describe the solution you would like

Introduce a GH action that runs the terraform provider against some of the popular scenarios from the [SAP-samples](https://github.com/SAP-samples/btp-terraform-samples) repository against internal landscape
Why

- A confidence in the compatibility and stability of the provider against updates
- Wider coverage of resources used in different ways
- Updated scenarios over time

**Comment by lechnerc77** [comment]
I think we can then close #596  as the result of this request will ensure the same goals with an even broader scope. Correct?

**Comment by vipinvkmenon** [comment]
Yes, that makes sense.
