### ISSUE TITLE
[Question] may I convert result from data source returns to resource?

### ISSUE THREAD

**Issue by superwangnan** [SAP/terraform-provider-btp#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.2.0

### What version of the Terraform CLI are you using?

1.8.2

### What type of issue are you facing

bug report

### Describe the bug

Hi team,

Just as title, I want to copy / backup subaccount for redeploy or setup a new subaccount. So, I want to know if there is a convenient way to convert the data source returns to resources directly. So, I don't need to key in every setting.

Thanks

**Comment by lechnerc77** [comment]
Van you please openn a question in the GitHub Discussion on this topic. This is neither a bug nor a Feature request
