### ISSUE TITLE
[BUG] unexpected error after enabling SSO in a dev container with TF CLI

### ISSUE THREAD

**Issue by rui1610** [SAP/terraform-provider-btp#804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.3.0

### What version of the Terraform CLI are you using?

1.8.2

### What type of issue are you facing

bug report

### Describe the bug

I wanted to test the SSO feature in v1.3.0 and set the env variable BTP_ENABLE_SSO to true.
When doing so, I’m getting the following error: 

│ Error: unableToCreateClient
│ 
│   with provider["registry.terraform.io/sap/btp"],
│   on provider.tf line 11, in provider "btp":
│   11: provider "btp" {
│ 
│ exec: "xdg-open": executable file not found in $PATH

Did I miss something or is there a specific pre-requisite?

### Expected Behavior

The login is done via SSO without any error messages.

### Steps To Reproduce

1. Open a dev container with pre-installed terraform CLI
2. Set the env variable BTP_ENABLE_SSO to true
3. Run a terraform script that uses the TF provider for SAP BTP

**Comment by rui1610** [comment]
Fixed the issue myself by adding 'xdg-open' to my dev container Dockerfile.
One can do it e.g. via running 'apt-get install xdg-utils' in a linux system.

**Comment by lechnerc77** [comment]
This is now part of the devcontainer setup for:

- The Terraform Provider for SAP BTP, see PR https://github.com/SAP/terraform-provider-btp/pull/805
- The Terraform [samples repository](https://github.com/SAP-samples/btp-terraform-samples):  see PR https://github.com/SAP-samples/btp-terraform-samples/pull/145
