### ISSUE TITLE
[FEATURE] Expose Terraform Plugin Framework Provider

### ISSUE THREAD

**Issue by sdischer-sap** [SAP/terraform-provider-btp#807]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

As part of our cooperation we use the terraform-provider-btp to power our crossplane based btp provider, which allows for continuous resource reconcilation. The technology being used here is based on [upjet](https://github.com/crossplane/upjet). 

In previous releases upjet is using a forked terraform process to leverage the providers CRUD functionality. In favor or performance and lowered resource consumption they now offer a more lightweight integration, in which the providers code can be run without involving a terraform process (see upjets [release ](https://github.com/crossplane/upjet/releases/tag/v1.1.0) and relevant [PR](https://github.com/crossplane/upjet/pull/329)). 

This new approach is a lot faster and consumes less memory, so we highly anticipate using the btp terraform provider in that way. 

### Describe the solution you would like

To leverage this approach the provider needs to be exposed, so that it can be used from the outside. 
Here is an example of how that has been done for the aws terraform provider: https://github.com/upbound/terraform-provider-aws/blob/upjet-v5.31.0/xpprovider/xpprovider.go#L30. 

### Additional context

Since implementing that is probably done best with trying its import into the crossplane provider I offer my/our help with contributing this feature set.

**Comment by lechnerc77** [comment]
The feature is not implemented by any official Terraform provider. It adds no value for customers using the provider in their Terraform setup.

If you want to use the mentioned new  upjet functionality and leverage the provider for the bridge implementation, please use the same mechanics as mentioned in the references, namely forking the provider and adding the change in the fork
