### ISSUE TITLE
[FEATURE] support directory entitlements

### ISSUE THREAD

**Issue by v0lkc** [SAP/terraform-provider-btp#81]
### What area do you want to see improved?

None

### Is your feature request related to a problem? Please describe.

A `btp_directory_entitlements` resource is missing so far.

### Describe the solution you would like

Similarly to the `btp_subaccount_entitlements` resource, we should have a resource to maintain entitlements on directory level.

**Comment by lechnerc77** [comment]
Closing in favor of #275  that contains the full functionality around directory features
