### ISSUE TITLE
[FEATURE]Quick start guide

### ISSUE THREAD

**Issue by CHERIANS** [SAP/terraform-provider-btp#811]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

End users of BTP terraform provider needs instruction for a quick start of using the provider

### Describe the solution you would like

Document in a readme minimal steps to get started using the terraform provider.

**Comment by lechnerc77** [comment]
@CHERIANS  Isn't this already covered by the developers.sap.com tutorial: https://developers.sap.com/tutorials/btp-terraform-get-started.html
Is there any information missing that should be added to the tutorial?

**Comment by lechnerc77** [comment]
Fixed by #813
