### ISSUE TITLE
[ORG] Developer Onboarding Concept

### ISSUE THREAD

**Issue by lechnerc77** [SAP/terraform-provider-btp#83]
To internally onboard new team members to SAP BTP Terraform provider in a Developer role the following the following steps need to be taken:

- [x] Windows or Mac computer available. There are no hardware limitations. Use dev containers
- [x] CAM Profile [BTP Terraform Developer](https://spc.ondemand.com/sap/bc/webdynpro/a1sspc/cam_wd_central?item=request&profile=BTP%20Terraform%20Developer) assigned
- [x] Set-up two days/meetings for Onboarding:
       - Day 1: Checking out "Get Started - SAP BTP" documentation, the "How to" process documentation for 
         Review/Pull-Requests/Release, and starting to use the Terraform Provider.
       - Day 2: Starting Pair-Programming with tasks marked as "Beginner Level" in the github repository to 
         gain hands on insights.

**Prerequisite for the Development Onboarding Concept**

- [x] Create "Get Started - SAP BTP" similar to the [AWS-Example](https://developer.hashicorp.com/terraform/tutorials/aws-get-started).
- [X] Create "Good first issue" label for Github and mark fitting tasks with that new label.
- [x] Create/Update the "How to" documentation for  Review/Pull-Requests/Release processes.
- [x] Create documentation on "How to do changes", "how to release a new version". and "How to gain all required access rights" for SAP BTP Terraform provider.
- [x] Create a template for the two onboarding meetings, including all relevant links to documentation and other required sources.

**Comment by v0lkc** [comment]
`How to do changes` has been documented with #211. Is this enough, or do you expect more @lechnerc77 ?
