### ISSUE TITLE
[FEATURE] Make timeouts on subscription resource configurable

### ISSUE THREAD

**Issue by vipinvkmenon** [SAP/terraform-provider-btp#848]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

Currently, the resource subscription has a default timeout of 10 minutes. Certain subscriptions take more time than this and thus needs to be configurable.

### Describe the solution you would like

New parameters for configuring timeouts for subscriptions similar to configuration available in service instance resource.

**Comment by lechnerc77** [comment]
Be aware that this enhancement might require a state upgrade (see < https://developer.hashicorp.com/terraform/plugin/framework/resources/state-upgrade>)

If an urgent fix is needed we can temporarily change the default value for this resource

**Comment by lechnerc77** [comment]
PR #856 provides a temporary workaround by increasing the timeout time for subscriptions. This should fix most cases.

On the mid-term we should enhance the resource to use the Terraform standard timeout block as available for environments and service instances. This change might imply a state upgrade as mentioned before.
