### ISSUE TITLE
[BUG] BTP_IDTOKEN silently takes precedence even when username and password are provided

### ISSUE THREAD

**Issue by z-mvg** [SAP/terraform-provider-btp#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.3.0

### What version of the Terraform CLI are you using?

1.9.2

### What type of issue are you facing

bug report

### Describe the bug

I recently faced a problem that I was getting a `Login failed. Invalid provider configuration. [Status: 400...`.

After much digging around and hit and trials, the issue turned out to be that I had tried set the BTP_IDTOKEN env variable and forgotten about it once it did not work. I then tried out setting username and password directly, but it still continued giving me the same login failed error as above with status 400. As soon as I unset the variable BTP_IDTOKEN, the login worked!

Unfortunately, neither the error not the detailed logs (TF_LOG = debug) contained either of the hint that  BTP_IDTOKEN was being considered for authentication or that BTP_IDTOKEN and user/password were both provided instead of only one of them. 

### Expected Behavior

To avoid this situation, the expectation would be that if BTP_IDTOKEN and user/password are provided at the same time, at least a warning should be logged that both have been provided along with the info on which takes precedence and will be considered. Could you please consider this?

Also, regarding BTP_IDTOKEN, the documentation mentions that it is SAP-internal usage only. However, even for internal users I am not sure if it is common knowledge on how to obtain this token (at least https://<<idp-host>>/service/users/passcode did not work for me). It would be great on some hint can be provided on this as well.

### Steps To Reproduce

Attaching my tf file as well as debug log output in case it would be of any help. To recreate:

1. Set any junk value to BTP_IDTOKEN variable
2. Use main.tf file as given below, substitute username placeholder
3. `terraform apply` and enter password when prompted

[main.tf.txt](https://github.com/user-attachments/files/16246796/main.tf.txt)
[debug.log](https://github.com/user-attachments/files/16246798/debug.log)

**Comment by lechnerc77** [comment]
@z-mvg Thanks for bringing this up. A fix is on the way that validates the parameters. An error message will be raised in accordance to the schema validation that was already in place

Concerning the *SAP-internal usage*: this should be used only by specific BTP cockpit integration scenarios which is the reason why we did not add any further documentation. 
The way 99.9% of users of the provider should use username/password flow.
