### ISSUE TITLE
[FEATURE] Support for Service Broker Registration

### ISSUE THREAD

**Issue by v0lkc** [SAP/terraform-provider-btp#855]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

The SAP BTP Terraform Provider currently lacks the capability to register service brokers that comply with the [Open Service Broker API specification](https://github.com/openservicebrokerapi/servicebroker/blob/v2.17/spec.md) within a BTP subaccount. The introduction of a new resource, namely `btp_subaccount_service_broker`, would fill this gap for integration testing of service brokers.

### Describe the solution you would like

Introduce a new resource, `btp_subaccount_service_broker`, to the Terraform Provider for SAP BTP. This resource will manage the lifecycle of service brokers within a subaccount. It will support creating, updating, and deleting service broker registrations.

Details for the new resource include:
- **subaccount_id**: Reference to the subaccount ID in which to register the broker.
- **name**: A unique name for the broker within the subaccount.
- **description**: Descriptive text to explain the broker's purpose.
- **url**: The URL pointing to the service broker's API endpoint.
- **username** and **password**: Credentials required for the platform to authenticate with the service broker.
- **labels**: Key-value pairs to provide additional metadata about the service broker.

### Example Configuration

```hcl
resource "btp_subaccount_service_broker" "broker" {
   subaccount_id = btp_subaccount.consumer.id
   name          = "my-broker"
   description   = "Service broker for provisioning example services."
   url           = "https://my.broker.com"

   username = "platform_user"
   password = "platform_password"

   labels = {
      environment = ["test"]
      version     = ["v1.0"]
   }
}
```

### Describe alternatives you have considered

* triggering the service manager cli for the onboarding using a `null_resource`
  * requires additional tooling to be preinstalled on the host
  * disrupts the terraform flow
  * doesn't perform offboarding
* triggering the onboarding using plain `http_get` requests to the service manager api with the http datasource
  * disrupts the terraform flow
  * doesn't perform offboarding

### Additional context

| Task | Command Reference |
|--------------------------------------------------------------|-----------------------------------------------------------------------|
| Get a specific service broker in the current subaccount | [`btp get services/broker`](https://help.sap.com/docs/BTP/btp-cli/btp-get-services-broker.html) |
| Register a new service broker in the current subaccount | [`btp register services/broker`](https://help.sap.com/docs/BTP/btp-cli/btp-register-services-broker.html) |
| Update an existing service broker in the current subaccount | [`btp update services/broker`](https://help.sap.com/docs/BTP/btp-cli/btp-update-services-broker.html) |
| Unregister an existing service broker in the current subaccount | [`btp unregister services/broker`](https://help.sap.com/docs/BTP/btp-cli/btp-unregister-services-broker.html) |

**Comment by lechnerc77** [comment]
Further information:

Datasource for service broker is available. The new resource would reflect the BTP CLI commands that represent the modification:

- Create/Register: <https://help.sap.com/docs/btp/btp-cli-command-reference/btp-register-services-broker>
- Update: <https://help.sap.com/docs/btp/btp-cli-command-reference/btp-update-services-broker>
- Delete/Unregister: <https://help.sap.com/docs/btp/btp-cli-command-reference/btp-unregister-services-broker>
