### ISSUE TITLE
[FEATURE] Add `dashboard_url` property to `btp_subaccount_service_instance` Resource and Data Source

### ISSUE THREAD

**Issue by markusbalsam** [SAP/terraform-provider-btp#864]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

Instances of certain BTP services have a dashboard URL. For these cases in BTP cockpit, the instance name is a link and user can access the dashboard by following it.

When a service instance is created with the Terraform provider for SAP BTP, or an existing instance is accessed as a data source, the dashboard URL is not available and users have to use other BTP clients like the CLI or the Cockpit to find out the URL.

### Describe the solution you would like

Add a read-only, nullable `dashboard_url` property to the `btp_subaccount_service_instance` resource and data source, so that users can get this URL from the state or use it as an output.

### Additional context

The BTP CLI already returns the `dashboard_url` for service instances:

```
$ btp --format JSON get services/instance --name free_datasphere-service
{
  "id": "...",
  "ready": true,
  "last_operation": {
    ...
  },
  ...
  "dashboard_url": "https://markus-test.us20.hcs.cloud.sap",
  "context": {
    ...
  },
 ...
}
```

**Comment by lechnerc77** [comment]
@markusbalsam are you aware of services besides datasphere that fill this attribute?

**Comment by markusbalsam** [comment]
@lechnerc77 From the top of my head, Application Logging and ABAP. Those services use the CF runtime though and can be created with the TF Provider for Cloud Foundry as a `cloudfoundry_service_instance`. That resource already has a `dashboard_url` property: https://registry.terraform.io/providers/SAP/cloudfoundry/latest/docs/resources/service_instance#dashboard_url.

In general, since both BTP Cockpit and CLI provide the `dashboard_url` if it exists, I thought it might be worth adding the property.

**Comment by lechnerc77** [comment]
> @lechnerc77 From the top of my head, Application Logging and ABAP. Those services use the CF runtime though and can be created with the TF Provider for Cloud Foundry as a `cloudfoundry_service_instance`. That resource already has a `dashboard_url` property: https://registry.terraform.io/providers/SAP/cloudfoundry/latest/docs/resources/service_instance#dashboard_url.
> 
> 
> 
> In general, since both BTP Cockpit and CLI provide the `dashboard_url` if it exists, I thought it might be worth adding the property.

Thanks for the input. It is not about implementing it (PR is already there) but how to best test it :-)
