### ISSUE TITLE
[FEATURE] Resource btp_subaccount_subscription to support Custom or partner-developed applications

### ISSUE THREAD

**Issue by stefania-santimbrean** [SAP/terraform-provider-btp#866]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

I wish to create an "n" number of subscriber subaccount and subscribe them to a multitenant (SaaS) app in order to have a similar number of subscribers like in a production enviroment with the end goal of stress testing the deployment/upgrade of HDI containers. Currently for this `main.tf` I see the following error when I run `terraform apply`:
```
variable "password" {
    type = string
    sensitive = true
}

variable "subaccount_name" {
    type = string
}

variable "global_account" {
  type = string
  default = "..."
}

variable "app"  {
  type = string
  default = "myCustomSaaSApp"
}

terraform {
  required_providers {
    btp = {
      source  = "sap/btp"
      version = "1.4.0"
    }
  }
}

provider "btp" {
  globalaccount = var.global_account
  username      = var.username
  password      = var.password
}

resource "btp_subaccount" "terraform-ace" {
  name        = var.subaccount_name
  subdomain   = var.subaccount_name
  region      = "eu20"
  description = "Hey, this subaccount is managed by Terraform!"
}

resource "btp_subaccount_subscription" "app" {
  subaccount_id = btp_subaccount.terraform-ace.id
  app_name      = var.app
  plan_name     = "default"
}
```
Error:
```
btp_subaccount_subscription.ace_app: Creating...
╷
│ Error: API Error Creating Resource Subscription (Subaccount)
│ 
│   with btp_subaccount_subscription.ace_app,
│   on main.tf line 65, in resource "btp_subaccount_subscription" "ace_app":
│   65: resource "btp_subaccount_subscription" "ace_app" {
│ 
│ Could not find application with name ace-live-st01 and plan default. Either the application or plan does not exist, or the subaccount is not entitled to
│ the specified application plan. [Error: 90017/409]
```

### Describe the solution you would like

I would like to be able to do it using resources. I am seeing here an example with this:

- https://github.com/SAP-samples/btp-cap-multitenant-saas/blob/main/docu/4-expert/btp-terraform-setup/files/subscriber/main.tf#L77
- https://github.com/SAP-samples/btp-cap-multitenant-saas/blob/main/docu/4-expert/btp-terraform-setup/README.md

For this example a SAP app is used or a custom one? Reading the code it looks to me like a custom one is used.

Is this supposed to be working? I am trying to subscribe a multitenant app from same global account.

### Describe alternatives you have considered

There is this alternative:
```
resource "null_resource" "btp_cf_setup" {
  provisioner "local-exec" {
    command = "btp login --url https://cpcli.cf.eu10.hana.ondemand.com --user ${var.username} --password ${var.password}"
  }

  provisioner "local-exec" {
    command = "btp subscribe accounts/subaccount --subaccount ${btp_subaccount.terraform-ace.id} --to-app ${var.app}"
  }
}
```
But btp cli is doing this in background so terraform is not aware if subscription is successful or not.

**Comment by stefania-santimbrean** [comment]
Hello @alperdedeoglu ,

What do you mean to compare "btp_subaccount_subscription" source?

Thanks,
Stefania

**Comment by alperdedeoglu** [comment]
Subscription is created via a resource type called "btp_subaccount_subscription" in this [file](https://github.com/SAP-samples/btp-cap-multitenant-saas/blob/main/docu/4-expert/saas-self-onboarding/files/terraform/main.tf). 

Please make sure that your SaaS Registry app name and plan name is precise and correct. It might be the reason that your app name or plan name are not matching therefore terraform provider can not find your application in the BTP Marketplace.

```tf
resource "btp_subaccount_subscription" "project" {
  subaccount_id = btp_subaccount.project.id
  app_name      = local.kyma ? "${var.app_name}-${var.namespace}-${var.shootname}" : "${var.app_name}-${var.space}-${var.org}"
  plan_name     = var.app_plan
}
```

**Comment by stefania-santimbrean** [comment]
Hello @alperdedeoglu ,

App name is for sure correct and plan name is "default" or to be more precise we do not specify a plan name when we configure the saas-registry service instance. But resource "btp_subaccount_subscription" has the field plan_name mandatory...

I am talking about a custom saas app. Subscription to HANA Tools for example works.

Thanks,
Stefania

**Comment by lechnerc77** [comment]
@stefania-santimbrean if you have no plan name for your application, this might cause issues. You can hand over an empty string, but I am not sure if this can cause problems with the saas manager. Can you register your app with an explicit plan name (e.g., `default`) and try the subscription to the app again?

**Comment by stefania-santimbrean** [comment]
Hello @lechnerc77 , @alperdedeoglu ,

Thanks for your suggestions! Indeed, I modified saas registry config in mta to have appPlan name default similar to this: https://github.com/SAP-samples/btp-cap-multitenant-saas/blob/main/deploy/cf/mta.yaml#L371 and it's now working!

Many thanks,
Stefania
