### ISSUE TITLE
[BUG] Templating does not work in error messages

### ISSUE THREAD

**Issue by holgpar** [SAP/terraform-provider-btp#870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.5.0

### What version of the Terraform CLI are you using?

tofu v1.7.2

### What type of issue are you facing

bug report

### Describe the bug

When reading subaccounts via the `btp_subaccount`  data source, I am seeing error message like this:

```
│ Error: API Error Reading Resource Subaccount : Please provide correct value for subdomain and region
│
│   with data.btp_subaccount.integration_test_to_import,
│   on import_test_accounts.tf line 20, in data "btp_subaccount" "integration_test_to_import":
│   20: data "btp_subaccount" "integration_test_to_import" {
│
│ Subaccount not found with subdomain  in region
```

### Expected Behavior

An error message which contains the actual values:

```
│ Error: API Error Reading Resource Subaccount : Please provide correct value for subdomain and region
│
│   with data.btp_subaccount.integration_test_to_import,
│   on import_test_accounts.tf line 20, in data "btp_subaccount" "integration_test_to_import":
│   20: data "btp_subaccount" "integration_test_to_import" {
│
│ Subaccount not found with subdomain "my-domain" in region "jp10"
```

By the way, for readability, it is better to use quoted values in messages (`%q`). Because if not and the value are empty for some reason one only sees to spaces with nothing in between...

### Steps To Reproduce

Just use a datasource wich tries to read a subaccount that does not exist.

**Comment by lechnerc77** [comment]
@holgpar Thanks for raising this issue. A fix is on its way and will be part of the next release.
