### ISSUE TITLE
[FEATURE] Add Attribute mapping in Subaccount Role Mapping Create

### ISSUE THREAD

**Issue by brahammittal** [SAP/terraform-provider-btp#878]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

Hi Team,

We are trying to mange the custom role collections in our BTP tenant via terraform. While we can create the role collections the attribute mapping to the SAML attributes is still a manual activity

Is it possible to get attribute mapping added via terraform ?

### Describe the solution you would like

Add attribute mapping into role collections via terraform

### Describe alternatives you have considered

Manual workaround

**Comment by brahammittal** [comment]
Yes I was looking for this only..thanks

**Comment by vipinvkmenon** [comment]
:)
