### ISSUE TITLE
[BUG] Cannot set a numeric quota to zero. Set an amount of zero (0) to remove an existing plan from an assigned directory or subaccount.

### ISSUE THREAD

**Issue by ptesny** [SAP/terraform-provider-btp#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.5.0

### What version of the Terraform CLI are you using?

1.9.0

### What type of issue are you facing

bug report

### Describe the bug

When trying to remove a numeric quota I'm getting the below error message. 

```
╷
│ Error: Invalid Attribute Value
│ 
│   with btp_subaccount_entitlement.free-trial-kymaruntime-quota,
│   on bootstrap-kymaruntime.tf line 24, in resource "btp_subaccount_entitlement" "free-trial-kymaruntime-quota":
│   24:   amount        = 0
│ 
│ Attribute amount value must be between 1 and 2000000000, got: 0
```

### Expected Behavior
[Set an amount of zero (0) to remove an existing plan from an assigned directory or subaccount.](https://help.sap.com/docs/btp/btp-cli-command-reference/btp-assign-accounts-entitlement#:~:text=Set%20an%20amount%20of%20zero%20(0)%20to%20remove%20an%20existing%20plan%20from%20an%20assigned%20directory%20or%20subaccount.
)

### Steps To Reproduce

/*
.PHONY: free-trial-kymaruntime-quota
free-trial-kymaruntime-quota: 
  btp assign accounts/entitlement --to-subaccount $$(btp list accounts/subaccount | jq -r '.value[] | select(.displayName == "trial") | .guid ') --for-service kymaruntime --plan trial --amount 0

*/

data "btp_subaccounts" "all" {}

resource "btp_subaccount_entitlement" "free-trial-kymaruntime-quota" {
  for_each      = { for sub in data.btp_subaccounts.all.values : sub.id => sub if sub.name == "trial" && var.BTP_KYMA_PLAN == "trial"}

  subaccount_id = each.key
  service_name  = "kymaruntime"
  plan_name     = var.BTP_KYMA_PLAN
  amount        = 0
}

### User's Role Collections

Subaccount Administrator

**Comment by CHERIANS** [comment]
@ptesny what could be the usecase to set entitlement to 0 instead of deleting the entitlement via terraform configuration. Setting entitlement value 0 via BTP CLI is same as removing the entitlement.

**Comment by ptesny** [comment]
@CHERIANS 

this is exactly what I am trying to do: to set the entitlement to zero:

```
data "btp_subaccounts" "all" {}

resource "btp_subaccount_entitlement" "free-trial-kymaruntime-quota" {
for_each = { for sub in data.btp_subaccounts.all.values : sub.id => sub if sub.name == "trial" && var.BTP_KYMA_PLAN == "trial"}

subaccount_id = each.key
service_name = "kymaruntime"
plan_name = var.BTP_KYMA_PLAN
amount = 0
}
```
However, btp provider restricts the amount value to `Attribute amount value must be between 1 and 2000000000, got: 0`

**Comment by ptesny** [comment]
> Also from the BTP cockpit one can never set the entitlement value to 0

Not correct. It is well documented and nicely working with BTP cli. 
The BTP cockpit uses this BTP cli feature (amount to zero) to allow to remove/delete an entitlement from the cockpit. 

Please read the doc: 
https://help.sap.com/docs/btp/btp-cli-command-reference/btp-assign-accounts-entitlement#:~:text=Set%20an%20amount%20of%20zero%20(0)%20to%20remove%20an%20existing%20plan%20from%20an%20assigned%20directory%20or%20subaccount.
 
For plans that have a numeric quota, use the '--amount' parameter to set the maximum allowed consumption (quota) of a plan for the directory or subaccount. Do not use the '--enable' parameter for these plans. Set an amount of zero (0) to remove an existing plan from an assigned directory or subaccount.

**Comment by lechnerc77** [comment]
@ptesny The approach you would like to achieve is not how Terraform works. Terraform is relying on a resource-based approach (unfortunately BTP is not) with CRUD and Import operations. Consequently there are some scenarios that might work with BTP tooling but a different approach (from BTP perspective, but standard when it comes to Terraform) is needed when managing the resources via Terraform. 

Hence, in case you want to remove a resource, you basically have remove the resource from the Terraform configuration, execute `terraform plan` and `terraform apply`.
Ther are variants deppending on the next steps you want to achieve like executing a `terraform destroy -target <Address Of The Resource>` to explicitly destroy one specific resource or a `terraform state rm` for removing the resource from the state, but if I understand your sceanrio correctly, then the first approach is the one that does the trick for you.

**Comment by CHERIANS** [comment]
@ptesny  in addition to what @lechnerc77  mentioned another workaround to achieve  what you want would be to use the [count  meta-argument ](https://developer.hashicorp.com/terraform/language/meta-arguments/count) which is by default 1 (if not specified).  Set count = 0 as shown in snippet below and if you do `terraform apply` the entitlement should be removed. When you want to add the entitlement again just set the count = 1 do `terraform apply` 
```
data "btp_subaccounts" "all" {}

resource "btp_subaccount_entitlement" "free-trial-kymaruntime-quota" {
for_each = { for sub in data.btp_subaccounts.all.values : sub.id => sub if sub.name == "trial" && var.BTP_KYMA_PLAN == "trial"}

subaccount_id = each.key
service_name = "kymaruntime"
plan_name = var.BTP_KYMA_PLAN
amount = 1
count = 0
}
```

**Comment by ptesny** [comment]
@lechnerc77 thanks for the heads up. 

IMO what is missing with the BTP TF provider is the ability to somehow manage the numeric quotas of the quota-based service plans separately from the resource entitlements.

We have the btp_globalaccount_entitlements (Data Source) but there is no btp_globalaccount_entitlements or btp_globalaccount_entitlement_quotas resource.

Anyway, there is a functional gap between BTPCLI and BTP TF provider with regard to the quota-based service plans and the quota distribution across a given BTP landscape.

**Comment by CHERIANS** [comment]
@ptesny how about the below code snippet

```
data "btp_subaccounts" "all" {}
amt = 0 /* entitlement amount */
resource "btp_subaccount_entitlement" "free-trial-kymaruntime-quota" {
for_each = { for sub in data.btp_subaccounts.all.values : sub.id => sub if sub.name == "trial" && var.BTP_KYMA_PLAN == "trial"}

subaccount_id = each.key
service_name = "kymaruntime"
plan_name = var.BTP_KYMA_PLAN
amount = var.amt >1 ?var.amt : 1
count = var.amt > = 1 ? 1 : 0
}
```

**Comment by ptesny** [comment]
```
╷
│ Error: Invalid combination of "count" and "for_each"
│ 
│   on bootstrap-kymaruntime.tf line 20, in resource "btp_subaccount_entitlement" "free-trial-kymaruntime-quota":
│   20:   for_each      = { for sub in data.btp_subaccounts.all.values : sub.id => sub if sub.name == "trial" }
│ 
│ The "count" and "for_each" meta-arguments are mutually-exclusive, only one should be used to be explicit about the
│ number of resources to be created.
╵
```

**Comment by ptesny** [comment]
fyi: I have implemented this missing BTP TF provider functionality using the TF [external provider's](https://registry.terraform.io/providers/hashicorp/external/latest/docs) [external data source](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/external) as a shell script with BTPCLI. 

- free-trial-kymaruntime-quota.tf

```
# https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/external
#
data "external" "free-trial-kymaruntime-quota" {
  program = ["bash", "${path.module}/free-trial-kymaruntime-quota.sh"]

  query = {
    # arbitrary map from strings to strings, passed to the external program as the data query.
    username = "${var.username}"
    password = "${var.password}"
    globalaccount = "${var.globalaccount}"
    url = "https://cli.btp.cloud.sap" 
  }
}
```

- free-trial-kymaruntime-quota.sh:

```
#!/bin/bash

set -e -o pipefail 
ISSUER=$(jq -r '{url: "\(.url)", username: "\(.username)", password: "\(.password)", globalaccount: "\(.globalaccount)" }' )
LOGIN=$(btp login \
--url $(jq  -r '. | .url' <<< $ISSUER ) \
--subdomain $(jq  -r '. | .globalaccount' <<< $ISSUER ) \
--user $(jq  -r '. | .username' <<< $ISSUER ) \
--password $(jq  -r '. | .password | tostring' <<< $ISSUER ))
QUOTA=$(btp assign accounts/entitlement --to-subaccount $(btp list accounts/subaccount | jq -r '.value[] | select(.displayName == "trial") | .guid ') --for-service kymaruntime --plan trial --amount 0)
jq -n --arg quota "$QUOTA" --arg issuer "$ISSUER"  '{"quota": $quota, "issuer": $issuer}'

```

- after apply from terraform.tfstate

```
    {
      "mode": "data",
      "type": "external",
      "name": "free-trial-kymaruntime-quota",
      "provider": "provider[\"registry.terraform.io/hashicorp/external\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "-",
            "program": [
              "bash",
              "./free-trial-kymaruntime-quota.sh"
            ],
            "query": {
              "globalaccount": "****-ga",
              "password": "****",
              "url": "https://cli.btp.cloud.sap",
              "username": "****"
            },
            "result": {
              "issuer": "{\n  \"url\": \"https://cli.btp.cloud.sap\",\n  \"username\": \"****\",\n  \"password\": \"******\",\n  \"globalaccount\": \"******l-ga\"\n}",
              "quota": "{\n  \"jobId\": \"48749261\"\n}"
            },
            "working_dir": null
          },
          "sensitive_attributes": []
        }
      ]
    },

```

**Comment by sp1goyal** [comment]
@CHERIANS @ptesny Since for_each and count meta-arguments can't be used together while creating a resource, I tried a workaround where we can have ternary operators in the for_each loop. We can have a variable named amount of type number and check whether the number is 0 or not based on the user input. If the condition is true will get the subaccount details and the amount attribute will take the value from the variable and accordingly resource can be created and entitlement can be assigned to directory or subaccount.

But I observed one more thing with this approach that if the condition fails we can return an empty set {} which will put all the attributes of the resources to null which automatically triggers 'terraform destoy' command and delete the resource as well as unassign the entitlement. 

Attaching code for reference
```
variable "amount" {
  type = number
  description = "Numeric Quota Input"
  default = 0
}
```

```
data "btp_subaccounts" "all" {}

resource "btp_subaccount_entitlement" "assign" {
  for_each = var.amount!=0 ? { for sub in data.btp_subaccounts.all.values : sub.id => sub if sub.name == "trial" && var.BTP_KYMA_PLAN == "trial"} : {}
  subaccount_id = each.key
  service_name = "kymaruntime"
  plan_name = var.BTP_KYMA_PLAN
  amount = var.amount
}
```

Attaching screenshots for reference:
<img width="1010" alt="Screenshot 2024-08-20 at 2 47 52 PM" src="https://github.com/user-attachments/assets/d1464c15-f97d-4a2c-b53f-e1c5e6f4515e">
<img width="1139" alt="Screenshot 2024-08-20 at 2 49 03 PM" src="https://github.com/user-attachments/assets/0fae5819-0463-4004-9457-7a5e5a8826b5">

**Comment by lechnerc77** [comment]
Closing this issue. Reason:

The resource for entitlements works in a Terraform compliant way offering the CRUD + LIST operations. We consistently mapped the BTP entitlement logic to this. No changes to the Terraform provider will be made.

In general, the flow for entitlements would also be questionable from a Terraform design perspective. Changes to the Infrastructure as Code should be transparent, consistent and follow an "as-Code" paradigm, namely changes in the infrastructure configuration should be done via pull requests that need to be reviewed. Sticking to Terraform a reviewer would expect a *removal* of a configuration (or a variable value) when a resource should be moved from am existing configuration. Achieving this via "magic" parameters would not be the preferred approach. Hence, removing the resource (in this case the entitlement) is the preferred approach in the declarative setup Terraform provides.
