### ISSUE TITLE
[FEATURE] remote backends: s3, HTTP and kubernetes secrets examples

### ISSUE THREAD

**Issue by ptesny** [SAP/terraform-provider-btp#885]
### What area do you want to see improved?

examples

### Is your feature request related to a problem? Please describe.

A backend defines where Terraform stores its [state](https://developer.hashicorp.com/terraform/language/state) data files.

Looking for an example of how to implement S3, kubernetes secret and HTTP based remote backends.

### Describe the solution you would like

This is to able to able to implement a sharable tf state solution.

**Comment by lechnerc77** [comment]
@ptesny samples and examples are usually located in the [Terraform samples repository](https://github.com/SAP-samples/btp-terraform-samples). Here you find examples for Kubernetes and Artifactory as state backend: https://github.com/SAP-samples/btp-terraform-samples/tree/main/released/terraform-be

If you want to see a Azure Blob Storage configuration, you can get some information here (in the context of drift detection:

- [blog post](https://dev.to/lechnerc77/terraform-provider-for-sap-btp-remote-state-and-drift-detection-3pnj)
- [repository](https://github.com/btp-automation-scenarios/btp-terraform-drift)

In general, the official documentation of Hashicorp is imho quite good when it comes to the configurations of the different backend (see [backend configuration](https://developer.hashicorp.com/terraform/language/settings/backends/configuration).

In case you have questions to a specific backend, feel free to start a [discussion](https://github.com/SAP/terraform-provider-btp/discussions).

**Comment by ptesny** [comment]
@lechnerc77,
Have you ever tried to use the BTP Object Store service as a backend for tf state ?
Do you think your azure blob sample [code](https://github.com/btp-automation-scenarios/btp-terraform-drift/blob/main/infra/provider.tf#L9) could work with the ObjectStore ?

**Comment by lechnerc77** [comment]
@ptesny no I did not. As the Object Store on BTP is an abstraction layer and I would assume that the APIs do not correspond to the "regular" APIs use in the backend implementations

**Comment by ptesny** [comment]
> @ptesny no I did not. As the Object Store on BTP is an abstraction layer and I would assume that the APIs do not correspond to the "regular" APIs use in the backend implementations

That's why I asked. It it did work it could have been a prominent way of getting the tf state houskept using an existing and affordable BTP service like the ObjectStore.

**Comment by ptesny** [comment]
@lechnerc77 
Do you know if terraform can be run as a k8s workload itself ?

For instance, this [guide](https://medium.com/@vinoji2005/using-terraform-with-kubernetes-a-comprehensive-guide-237f6bbb0586) describes how to use a tf Kubernetes provider, but terraform is still run from a terminal

**Comment by lechnerc77** [comment]
Usually you run Terraform from a CI/CD pipeline. You can put the TF binary into a container and deploy/execute the container where you want. 
The Cloud Automation Team at SAP leverages the approach with TF in a short-lived container inside a K8s cluster. The service is called via REST comprising the Terraform configuration as payload of the request

**Comment by ptesny** [comment]
What about this **terraformer** guy? https://github.com/gardener/terraformer ; have you ever used it ? is it what the aforementioned Cloud Automation Team does ?
