### ISSUE TITLE
[BUG] Provider Login via IDP

### ISSUE THREAD

**Issue by brahammittal** [SAP/terraform-provider-btp#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.6.0

### What version of the Terraform CLI are you using?

1.8.0

### What type of issue are you facing

documentation issue

### Describe the bug

Hi Team,

We are using Azure as IDP for our BTP landscape. We have been using Default IDP for out terraform needs. We would like to use our custom IDP for terraform authentication. I would like to understand if it is possible to use the IDP option in our case.

We are not replicating users into custom IAS.

Regards
Braham

### Expected Behavior

Want to know if the IDP option can be used in our case.

### Steps To Reproduce

Use the IDP option with terraform provider. Where IAS does not get users from IDP.

### User's Role Collections

Global Admin

### Add screenshots to help explain your problem

NA

### Additional context

NA

**Comment by lechnerc77** [comment]
@brahammittal I do not fully understand this issue: Are you running into an issue when authenticating via your custom IdP? Or is this a question on how to use the Terraform provider with the custom IdP.

If you have an issue, we need the information how to reproduce the issue based on your Terraform configuration.

If this is a question: if you are using a custom IdP for authentication you can specify the IdP via the provider configuration as described in the [Terraform registry](https://registry.terraform.io/providers/SAP/btp/latest/docs). The relevant field is [`idp`](https://registry.terraform.io/providers/SAP/btp/latest/docs#idp) where you specify the IdP as defined in the trust setup of your SAP BTP account.

**Comment by brahammittal** [comment]
As I said we have Azure as our IDP and we do not replicate the users to IAS, when I use IAS server which is maintained in trust config I get a 401. When I use Azure tenant link in I get 400 error.

provider "btp" {
   globalaccount = "globalaccount"
   username = var.admin
   password = var.password
   idp = IAS or Azure link
}

Hope this helps. We can have a call if need be to show what we have and then get the guidance

**Comment by brahammittal** [comment]
Able to login closing the issue.

**Comment by lechnerc77** [comment]
Good to hear that it works. If you have further questions I recommend to ask them in the [discussion area](https://github.com/SAP/terraform-provider-btp/discussions) of the repository as Q&A..
