### ISSUE TITLE
[FEATURE] resource btp_globalaccount_entitlement to set entitlements to the global account

### ISSUE THREAD

**Issue by marcorosa** [SAP/terraform-provider-btp#927]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

Hi colleagues, I watched your presentation in TechED and also did [your tutorial here](https://developers.sap.com/tutorials/btp-terraform-get-started..html), so you may be already aware of such missing feature.

Indeed, when `btp_subaccount_entitlement` is used, if the global account doesn't already have assigned the service, or it has the service but it doesn't have an entitlement available, then the execution fails.
See here the error raised when following your example without assigning alert-notification service and entitlement to the global account:
```
 Error: API Error Creating Resource Entitlement (Subaccount)
│ 
│   with btp_subaccount_entitlement.alert_notification_service,
│   on main.tf line 13, in resource "btp_subaccount_entitlement" "alert_notification_service":
│   13: resource "btp_subaccount_entitlement" "alert_notification_service" {
│ 
│ Cannot assign service alert-notification and plan standard to subaccount SSSSSSSSS. The global
│ account GGGGGGGGGG of this subaccount is not entitled to this service plan. [Error: 30015/409]
╵
```

Generated by (extract of `main.tf`)
```
resource "btp_subaccount_entitlement" "alert_notification_service" {
  subaccount_id = btp_subaccount.sa_build.id
  service_name  = "alert-notification"
  plan_name     = "standard"
}
```

### Describe the solution you would like

I think what's missing here is a resource `btp_globalaccount_entitlement` to assign a services to the global account (in case it's not assigned yet), and set an entitlement.

### Describe alternatives you have considered

An alternative could be integrating the assignment of the service and the quota in  `btp_subaccount_entitlement`, but that would only work if the user running terraform is also a global account admin.

**Comment by lechnerc77** [comment]
@marcorosa : The entitlements on global account level are part of the commercial model ie.e. the contract between SAP and the customer. They cannot be influenced by Terraform. 

- For a PAYG account or an account that is subject to CPEA/BTPEA the entitlements are available. Concerning this tutorial the same is true for a SAP BTP trial account.
- In case of a subscription based model, it depends on your setup and you might need to get in touch with your account executive to get additional entitlements needed for your scenario. 
- In case that you are using an SAP internal global account, @CHERIANS already esnt you an email describing how to assign the entitlements via SAP -internal tooling.

I am closing this issue as this resource won't be implemented.
