### ISSUE TITLE
[BUG] Assign list of  roles a list of users

### ISSUE THREAD

**Issue by jizquga** [SAP/terraform-provider-btp#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.7.0

### What version of the Terraform CLI are you using?

1.8.0

### What type of issue are you facing

bug report

### Describe the bug

We want to assign more than one role a list of users, we are use this main.tf:

resource "btp_subaccount_role_collection_assignment" "subaccount-seguridad" {
  subaccount_id        = "19545252-3943-46d9-a893-72841d94f332"
  role_collection_name = "Subaccount Viewer"
  for_each             = toset(var.seguridad)
  user_name            = each.value

}

But we want to change role_collection_name to a list of roles. Can you help us?

**Comment by lechnerc77** [comment]
@jizquga As mentioned in issue #926 please do not abuse issues for question. I kindly advice you to use the discussions area. Happy to answer these questions there
