### ISSUE TITLE
SAP IAS as a proxy to Azure

### ISSUE THREAD

**Issue by Alixis95** [SAP/terraform-provider-btp#960]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

Hello everyone,
I have configured SAP IAS as a proxy and Azure as IdP. I want users coming from the IdP (Azure) to log in with an employee ID in Cloud Apps. Is that possible?
Many Thanks

### Describe the solution you would like

Login in with Employee ID

### Describe alternatives you have considered

Login in with Employee ID

### Additional context

Login in with Employee ID

**Comment by lechnerc77** [comment]
@Alixis95 Not sure if I understand your question correctly and also do not see the connection to the Terraform provider. 

If you configured a custom IDP in SAP Cloud Identity Services you can create the trust to the provider in SAP BTP by configuring it via the corresponding resources (`btp_*_trust_configuration`). This alows your platform users to use the custom IDP (https://help.sap.com/docs/btp/sap-business-technology-platform/platform-users-440131674b0147a09e696053a53832d5?locale=en-US). Are you having issues with using this Terraform resource to establish the trust?

In case of question that are not related to the Terraform provider for SAP, I recommend to use the [SAP Community](https://community.sap.com/) for the request

**Comment by lechnerc77** [comment]
Closed as stale
